---
permalink: config-admin/about-oncommand-insight-anomaly-detection.html 
sidebar: sidebar 
keywords:  
summary: OnCommand Insight umfasst Analysen zur Anomalieerkennung auf Machine Learning, die eine Übersicht über die Applikationsinfrastruktur bieten und Performance-Anomalien identifizieren, bevor sie zu einer Service-Unterbrechung werden. 
---
= Funktionsweise der Erkennung von OnCommand Insight-Anomalien
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
OnCommand Insight umfasst Analysen zur Anomalieerkennung auf Machine Learning, die eine Übersicht über die Applikationsinfrastruktur bieten und Performance-Anomalien identifizieren, bevor sie zu einer Service-Unterbrechung werden.

Mithilfe einer Anomalieanalyse können Sie den normalen Workload-Bereich für eine Applikation identifizieren und Informationen darüber erhalten, wenn Performance-Änderungen außerhalb des erwarteten Levels liegen. Das Erkennungsmodul für Applikationsanomalien erfasst Performance-Kennzahlen, die von Insight erfasst werden, und ermittelt Anomalien in der Applikationsinfrastruktur.

Sie können die Anomalieerkennung verwenden, um folgende Aufgaben auszuführen:

* Ermitteln Sie wesentliche Änderungen im Verhalten der Applikationsinfrastruktur
* Verfolgen Sie eine Anwendung durch den gesamten Stack und über mehrere Zähler hinweg
* Diagnostizieren Sie die Ursache periodischer wiederkehrender Ereignisse in einem Applikations-Workload
* Stellen Sie einen umfassenderen Satz von Informationen im Vergleich zu Daten von Leistungsindikatoren mit statischen Schwellenwerten bereit
* Die Überwachung erfolgt in einem verbesserten reaktiven Modus, mit einer End-to-End-Ansicht der Topologie und der Fähigkeit, sich auf die ungewöhnlichsten Verhaltensweisen zu konzentrieren.


Das Erkennungsmodul für Anomalien verwendet Insight-Daten für Applikationsanalysen. Beim ersten Start der Überwachung können bis zu 14 Tage historische Leistungsdaten von der Analyse-Engine aufgenommen werden. Daten werden über Wochen oder sogar Monate hinweg erfasst, sodass genauere Daten über die jeweiligen Ressourcen bereitgestellt werden können. Die Daten enthalten Summen für die folgenden Zähler:

|===


| Objekte | Zähler 


 a| 
VM
 a| 
Latenz, IOPS



 a| 
Hypervisor
 a| 
CPU-Auslastung, IOPS



 a| 
Edge-Port
 a| 
BB Gutschrift Null



 a| 
Storage-Node
 a| 
Latenz, Auslastung, IOPS



 a| 
Datenmenge
 a| 
Latenz, IOPS



 a| 
Internes Volumen
 a| 
Latenz, IOPS



 a| 
Storage-Pool
 a| 
IOPS, Auslastung

|===
Die von der Anomalieerkennung erfassten Daten werden archiviert, wenn die Performance Data Archiving auf dem Insight Server aktiviert ist. Prüfen Sie auf der Seite Systemstatus, ob die Archivierung aktiviert ist.

Das Erkennungsmodul für Anomalien wird auf einem separaten Server als der Insight-Server ausgeführt. Sie kann auf einem physischen Rechner oder einer VM konfiguriert werden. Weitere Informationen finden Sie im OnCommand Insight Installationshandbuch für Windows oder Linux.
