---
permalink: config-admin/anomalies.html 
sidebar: sidebar 
keywords:  
summary: Der Abschnitt „Anomalien“, der nur auf einer Applikations-Asset-Seite angezeigt wird, wenn das Engine zur Erkennung von Anomalien installiert ist, ermöglicht Ihnen, den normalen Workload-Bereich für eine Applikation zu identifizieren und zu erkennen, wenn Performance-Änderungen außerhalb des erwarteten Levels liegen. 
---
= Anomalien
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der Abschnitt „Anomalien“, der nur auf einer Applikations-Asset-Seite angezeigt wird, wenn das Engine zur Erkennung von Anomalien installiert ist, ermöglicht Ihnen, den normalen Workload-Bereich für eine Applikation zu identifizieren und zu erkennen, wenn Performance-Änderungen außerhalb des erwarteten Levels liegen.

Eine Anomalieanalyse bietet proaktive Einblicke in die Infrastruktur zur Unterstützung von geschäftskritischen Applikationen und informiert Sie über Performance-Anomalien, bevor es zu einer Störung der Services kommt. Das Erkennungsmodul für Applikationsanomalien erfasst Performance-Kennzahlen, die von Insight erfasst werden, und ermittelt Anomalien in der Applikationsinfrastruktur. Anomalien sind Elemente, Ereignisse oder Beobachtungen, die nicht einem erwarteten Muster oder anderen Elementen entsprechen. Die Anomalieerkennung ermöglicht Folgendes:

* Überwachen Sie ausgewählte kritische Anwendungen.
* Ermitteln Sie wesentliche Änderungen im Verhalten der Applikationsinfrastruktur.
* Verfolgen Sie eine Anwendung durch den gesamten Stack und über mehrere Zähler hinweg.
* Diagnostizieren Sie die Ursache periodischer wiederkehrender Ereignisse in einem Applikations-Workload.
* Stellen Sie einen umfassenderen Satz von Informationen im Vergleich zu Daten von Leistungsindikatoren mit statischen Schwellenwerten bereit.
* Verbesserte Überwachung des Reaktionsmodus mit End-to-End-Ansicht der Topologie und der Fähigkeit, sich auf die ungewöhnlichsten Verhaltensweisen in einem Datensatz zu konzentrieren.

