---
permalink: config-admin/cdot-landing-page-terminology-storage-node.html 
sidebar: sidebar 
keywords:  
summary: Bedingungen für Objekte oder Referenzen, die auf den Storage-Node-Ressourcen-Landing-Pages von NetApp Clustered Data ONTAP zu finden sind. 
---
= Storage-Node von Clustered Data ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bedingungen für Objekte oder Referenzen, die auf den Storage-Node-Ressourcen-Landing-Pages von NetApp Clustered Data ONTAP zu finden sind.



== Clustered Data ONTAP – Terminologie für Storage-Nodes

Die folgenden Begriffe gelten für Objekte oder Verweise, die auf den Landing Pages für NetApp Clustered Data ONTAP Storage-Pool-Ressourcen möglicherweise zu finden sind. Viele dieser Bedingungen gelten auch für andere Datensammler.

* Storage – zu welchem Speicher-Array dieser Node gehört. Obligatorisch.
* HA Partner -- auf Plattformen, bei denen ein Knoten auf einen und nur einen anderen Knoten umfunktioniert, wird er hier im Allgemeinen angezeigt.
* Status – Systemzustand des Node. Nur verfügbar, wenn das Array ordnungsgemäß genug ist, um von einer Datenquelle inventarisiert zu werden.
* Model – Modellname des Knotens.
* Version -- Versionsname des Geräts.
* Seriennummer -- die Seriennummer des Node.
* Speicher -- Basis-2-Speicher, falls verfügbar.
* Auslastung: Bei ONTAP handelt es sich um einen Controller-Stress-Index eines proprietären Algorithmus. Bei jeder Performance-Umfrage wird anhand einer Zahl zwischen 0 und 100 % angegeben, die der höhere Wert bei WAFL-Festplattenkonflikten oder der durchschnittlichen CPU-Auslastung ist. Wenn Sie kontinuierliche Werte von > 50 % beobachten, ist das Anhaltspunkt dafür, dass die Größe nicht ausreichend ist – möglicherweise ist ein Controller/Node nicht groß genug oder nicht genug rotierende Festplatten, um den Schreib-Workload abzufangen.
* IOPS – direkt von ONTAP-ZAPI-Aufrufen auf dem Node-Objekt abgeleitet.
* Latenz – direkt von ONTAP-ZAPI-Aufrufen des Node-Objekts abgeleitet.
* Durchsatz -- direkt von ONTAP-ZAPI-Aufrufen des Node-Objekts abgeleitet.
* Prozessoren – CPU-Anzahl.

