---
permalink: config-admin/changing-user-passwords.html 
sidebar: sidebar 
keywords:  
summary: Ein Benutzer mit Administratorrechten kann das Kennwort für jedes auf dem lokalen Server definierte OnCommand Insight-Benutzerkonto ändern. 
---
= Benutzerpasswörter werden geändert
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ein Benutzer mit Administratorrechten kann das Kennwort für jedes auf dem lokalen Server definierte OnCommand Insight-Benutzerkonto ändern.



== Bevor Sie beginnen

Die folgenden Punkte müssen abgeschlossen sein:

* Benachrichtigungen an alle Personen, die sich bei dem Benutzerkonto anmelden, das Sie ändern möchten.
* Neues Passwort, das nach dieser Änderung verwendet werden soll.




== Über diese Aufgabe

Bei Verwendung dieser Methode können Sie das Kennwort für einen Benutzer, der über LDAP validiert wird, nicht ändern.



== Schritte

. Melden Sie sich mit Administratorrechten an.
. Klicken Sie in der Insight-Symbolleiste auf *Admin*.
. Klicken Sie Auf *Setup*.
. Klicken Sie auf die Registerkarte *Users*.
. Suchen Sie die Zeile, in der das Benutzerkonto angezeigt wird, das Sie ändern möchten.
. Rechts neben den Benutzerinformationen klicken Sie auf *Benutzerkonto bearbeiten*.
. Geben Sie das neue *Passwort* ein und geben Sie es dann erneut in das Bestätigungsfeld ein.
. Klicken Sie Auf *Speichern*.

