---
permalink: config-admin/changing-oncommand-insight-internal-user-passwords.html 
sidebar: sidebar 
keywords:  
summary: In Sicherheitsrichtlinien müssen Sie möglicherweise die Passwörter in Ihrer OnCommand Insight-Umgebung ändern. Einige der Passwörter auf einem Server sind auf einem anderen Server in der Umgebung vorhanden, sodass Sie das Passwort auf beiden Servern ändern müssen. Wenn Sie beispielsweise das Benutzerpasswort „Inventar“ auf dem Insight Server ändern, müssen Sie das Benutzerpasswort „Inventar“ auf dem für diesen Insight Server konfigurierten Data Warehouse Server Connector übereinstimmen. 
---
= Ändern der internen OnCommand Insight-Benutzerpasswörter
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
In Sicherheitsrichtlinien müssen Sie möglicherweise die Passwörter in Ihrer OnCommand Insight-Umgebung ändern. Einige der Passwörter auf einem Server sind auf einem anderen Server in der Umgebung vorhanden, sodass Sie das Passwort auf beiden Servern ändern müssen. Wenn Sie beispielsweise das Benutzerpasswort „`inventar`“ auf dem Insight Server ändern, müssen Sie das Benutzerpasswort „`inventar`“ auf dem für diesen Insight Server konfigurierten Data Warehouse Server Connector zuordnen.



== Bevor Sie beginnen

[NOTE]
====
Sie sollten die Abhängigkeiten der Benutzerkonten verstehen, bevor Sie Passwörter ändern. Wenn Passwörter nicht auf allen erforderlichen Servern aktualisiert werden, kommt es zu Kommunikationsfehlern zwischen den Insight-Komponenten.

====


== Über diese Aufgabe

In der folgenden Tabelle sind die internen Benutzerpasswörter für den Insight Server aufgeführt und die Insight-Komponenten mit abhängigen Kennwörtern aufgeführt, die mit dem neuen Passwort übereinstimmen müssen.

|===


| Passwörter Für Insight Server | Erforderliche Änderungen 


 a| 
_Intern
 a| 



 a| 
Akquisition
 a| 
LAU, RAU



 a| 
dwh_intern
 a| 
Data Warehouse



 a| 
Hosts
 a| 



 a| 
Inventar
 a| 
Data Warehouse



 a| 
Stamm
 a| 

|===
In der folgenden Tabelle sind die internen Benutzerkennwörter für das Data Warehouse und die Insight-Komponenten mit abhängigen Kennwörtern aufgeführt, die mit dem neuen Kennwort übereinstimmen müssen.

|===


| Data Warehouse-Passwörter | Erforderliche Änderungen 


 a| 
cognos_admin
 a| 



 a| 
dwh
 a| 



 a| 
dwh_Internal (geändert mit der Server Connector-Konfigurationsoberfläche)
 a| 
Insight Server



 a| 
Whuser
 a| 



 a| 
Hosts
 a| 



 a| 
Inventarisierung (geändert mit der Server Connector-Konfigurationsoberfläche)
 a| 
Insight Server



 a| 
Stamm
 a| 

|===
*Ändern von Kennwörtern in der DWH Server Connection Configuration UI*

In der folgenden Tabelle ist das Benutzerpasswort für DIE LAU aufgeführt und die Insight-Komponenten mit abhängigen Kennwörtern, die mit dem neuen Passwort übereinstimmen müssen.

|===


| LAU-Passwörter | Erforderliche Änderungen 


 a| 
Akquisition
 a| 
Insight Server, rau

|===