---
permalink: config-admin/cognos-configuration-for-smart-card-and-certificate-login-7-3-10-and-later.html 
sidebar: sidebar 
keywords:  
summary: 'Sie müssen die Konfiguration des OnCommand Insight Data Warehouse ändern, um Smart Card \ (CAC\) und Zertifikatanmeldungen für den Cognos-Server zu unterstützen.' 
---
= Konfigurieren von Cognos für Smart Card- und Zertifikatanmeldung (OnCommand Insight 7.3.10 und höher)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie müssen die Konfiguration des OnCommand Insight Data Warehouse ändern, um Smart Card- (CAC) und Zertifikatanmeldungen für den Cognos-Server zu unterstützen.



== Bevor Sie beginnen

Dieses Verfahren gilt für Systeme mit OnCommand Insight 7.3.10 und höher.

[NOTE]
====
Die aktuellsten CAC- und Zertifikatanweisungen finden Sie in den folgenden Knowledgebase-Artikeln (Support-Anmeldung erforderlich):

* https://kb.netapp.com/Advice_and_Troubleshooting/Data_Infrastructure_Management/OnCommand_Suite/How_to_configure_Common_Access_Card_(CAC)_authentication_for_NetApp_OnCommand_Insight["So konfigurieren Sie die Common Access Card (CAC)-Authentifizierung für OnCommand Insight"]
* https://kb.netapp.com/Advice_and_Troubleshooting/Data_Infrastructure_Management/OnCommand_Suite/How_to_configure_Common_Access_Card_(CAC)_authentication_for_NetApp_OnCommand_Insight_DataWarehouse["Konfigurieren der Authentifizierung für allgemeine Zugriffskarten (Common Access Card, CAC) für OnCommand Insight Data Warehouse"]
* https://kb.netapp.com/Advice_and_Troubleshooting/Data_Infrastructure_Management/OnCommand_Suite/How_to_create_and_import_a_Certificate_Authority_(CA)_signed_certificate_into_OCI_and_DWH_7.3.X["Erstellen und Importieren eines signierten Zertifikats einer Zertifizierungsstelle (CA) in OnComand Insight und OnCommand Insight Data Warehouse 7.3.x"]
* https://kb.netapp.com/Advice_and_Troubleshooting/Data_Infrastructure_Management/OnCommand_Suite/How_to_create_a_Self_Signed_Certificate_within_OnCommand_Insight_7.3.X_installed_on_a_Windows_Host["So erstellen Sie ein selbstsigniertes Zertifikat in OnCommand Insight 7.3.X, das auf einem Windows-Host installiert ist"]
* https://kb.netapp.com/Advice_and_Troubleshooting/Data_Infrastructure_Management/OnCommand_Suite/How_to_import_a_Cognos_Certificate_Authority_(CA)_signed_certificate_into_DWH_7.3.3_and_later["Importieren eines von Cognos signierten Zertifikats einer Zertifizierungsstelle (CA) in OnCommand DataWarehouse 7.3.3 und höher"]


====


== Schritte

. Fügen Sie dem Cognos trustore Zertifizierungsstellen (CAS) hinzu.
+
.. Wechseln Sie in einem Befehlsfenster zu `..\SANscreen\cognos\analytics\configuration\certs\`
.. Verwenden Sie die `keytool` Dienstprogramm zum Auflisten der vertrauenswürdigen CAS: `..\..\ibm-jre\jre\bin\keytool.exe -list -keystore CAMKeystore.jks -storepass NoPassWordSet`
+
Das erste Wort in jeder Zeile gibt den CA-Alias an.

.. Wenn keine geeigneten Dateien vorhanden sind, geben Sie eine Zertifizierungsstellenzertifikatsdatei an, in der Regel eine `.pem` Datei:
.. Wenn Sie Zertifizierungsstellen des Kunden mit vertrauenswürdigen Zertifizierungsstellen von OnCommand Insight einbeziehen möchten, besuchen Sie `..\SANscreen\cognos\analytics\configuration\certs\`.
.. Verwenden Sie die `keytool` Dienstprogramm zum Importieren des `.pem` Datei: `..\..\ibm-jre\jre\bin\keytool.exe -importcert -keystore CAMKeystore.jks -alias my_alias -file 'path/to/my.pem' -v -trustcacerts`
+
`my_alias` Ist in der Regel ein Alias, der die CA in der leicht identifizieren würde``keytool -list`` Betrieb.

.. Wenn Sie zur Eingabe eines Passworts aufgefordert werden, geben Sie ein `NoPassWordSet`.
.. Antwort `yes` Wenn Sie aufgefordert werden, dem Zertifikat zu vertrauen.


. Gehen Sie wie folgt vor, um den CAC-Modus zu aktivieren:
+
.. Konfigurieren Sie die CAC-Abmeldeseite mit den folgenden Schritten:
+
*** Anmeldung beim Cognos-Portal (Benutzer muss Teil der Gruppe „Systemadministratoren“ sein, d. h. cognos_admin)
*** (Nur für 7.3.10 und 7.3.11) Klicken Sie auf Verwalten \-> Konfiguration \-> System \-> Sicherheit
*** (Nur für 7.3.10 und 7.3.11) Geben Sie cacLogout.html gegen Abmeldung ein Umleiten Sie die URL \-> Anwenden
*** Browser schließen.


.. Ausführen `..\SANscreen\bin\cognos_cac\enableCognosCAC.bat`
.. Starten Sie den IBM Cognos-Dienst. Warten Sie, bis der Cognos-Dienst gestartet wird.


. Gehen Sie wie folgt vor, um den CAC-Modus zu deaktivieren:
+
.. Ausführen `..\SANscreen\bin\cognos_cac\disableCognosCAC.bat`
.. Starten Sie den IBM Cognos-Dienst. Warten Sie, bis der Cognos-Dienst gestartet wird.
.. (Nur für 7.3.10 und 7.3.11) Unconfigure CAC Logout page, mit den folgenden Schritten:
+
*** Anmeldung beim Cognos-Portal (Benutzer muss Teil der Gruppe „Systemadministratoren“ sein, d. h. cognos_admin)
*** Klicken Sie Auf Verwalten \-> Konfiguration \-> System \-> Sicherheit
*** Geben Sie cacLogout.html für die URL zur Umleitung von Abmeldung ein \-> Anwenden
*** Browser schließen.





