---
permalink: config-admin/configuring-client-settings.html 
sidebar: sidebar 
keywords:  
summary: Sie können Optionen für den OnCommand Insight Java UI Client auf dem Server konfigurieren. 
---
= Konfigurieren der Client-Einstellungen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können Optionen für den OnCommand Insight Java UI Client auf dem Server konfigurieren.



== Schritte

. Klicken Sie in der Insight-Symbolleiste auf *Admin* und wählen Sie *Fehlerbehebung*.
. Klicken Sie unten auf der Seite im Bereich Weitere Aufgaben auf den Link *Erweiterte Fehlerbehebung*.
. Klicken Sie im Menü Erweitert auf der nächsten Seite auf die Registerkarte *Erweiterte Einstellungen*.
. Geben Sie im Feld *Acquisition Dynamic Attributes* die Anzahl der Stunden ein, um dynamische Attributänderungen zu ignorieren.
. Geben Sie in *Configure Client Settings* die folgenden Informationen ein.
+
** *Initial Heap Size* ist die Größe des Heaps, der erstellt wird, wenn die VM (Virtual Machine) gestartet wird, um den Client auszuführen. Diese Nummer wird verwendet, um das zu erstellen``-Xms<size>`` Parameter an `java`. Eine Verringerung dieser Zahl bedeutet, dass Java weniger Speicher benötigt, wenn es gestartet wird. (Allerdings ist es dann wahrscheinlicher, dass Java den Heap neu zuordnen muss, wenn er diese Zahl überschreitet, was eine teure Operation ist, so dass Sie diese Zahl nicht zu klein machen möchten.)
** *Max Heap Size* ist die größte, die Java dem Heap erlaubt, in der VM zu wachsen, auf der der Client ausgeführt wird. Diese Nummer wird verwendet, um das zu erstellen``-Xmx<size>`` Parameter an `java`.
** Die Protokollebene steuert die Menge an Details, die in den Clientprotokollen generiert werden. Es gibt zwei mögliche Werte:
+
*** INFO - erzeugt eine „normale“ Menge an Informationen.
*** DEBUG – generiert ausführlichere Informationen für das Clientprotokoll, um beim Debuggen zu helfen.




. Konfigurieren Sie die Datenquellwarnungen.
. Konfigurieren Sie die vom Client angezeigte Warnmeldung für die Anmeldung.
. Klicken Sie Auf *Speichern*.

