---
permalink: config-admin/configuring-anomaly-detection-for-applications.html 
sidebar: sidebar 
keywords:  
summary: Sie müssen die Anomalieerkennung aktivieren, um die Infrastruktur einer Applikation auf ungewöhnliches Verhalten zu überwachen. Das Monitoring der Anomalieerkennung wird nur für Applikationen ein- oder ausgeschaltet. 
---
= Konfigurieren von Anwendungen für die Erkennung von Anomalien
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie müssen die Anomalieerkennung aktivieren, um die Infrastruktur einer Applikation auf ungewöhnliches Verhalten zu überwachen. Das Monitoring der Anomalieerkennung wird nur für Applikationen ein- oder ausgeschaltet.



== Bevor Sie beginnen

* Sie müssen das Engine zur Erkennung von Anomalien installiert und konfiguriert haben.
* Sie müssen der Compute-Ressource (Virtual Machine oder Host) eine Anwendung für alle Assets zugewiesen haben, für die Sie Informationen zur Anomalieerkennung benötigen. Insight erkennt die restlichen Ressourcen automatisch.




== Schritte

. Melden Sie sich bei der OnCommand Insight Web-Benutzeroberfläche an.
. Klicken Sie auf *Verwalten* und wählen Sie *Anwendungen*.
. Suchen Sie die Anwendung, die der Rechenressource zugewiesen ist.
. Stellen Sie im Abschnitt *Anomalien* sicher, dass das Kontrollfeld *Monitor* oben rechts im Abschnitt *EIN* statt *AUS* anzeigt; wenn nicht, klicken Sie auf eine beliebige Stelle im Kontrollfeld *Monitor*, um das Steuerelement auf *EIN* zu schalten.
+
Sie können bis zu 48 Anwendungen gleichzeitig auf Anomalien überwachen.

+
Der Status im Abschnitt zeigt „`Learning`“ mindestens eine Stunde lang an. Das Engine zur Erkennung von Anomalien lädt bis zu 14 Tage vorhandene Performance-Daten voraus, sodass die Engine das Verhalten Ihrer Umgebung lernen kann. Nachdem der Insight-Server die erste Abfrage der Ressourcen Ihrer Umgebung durchgeführt hat, berechnet das Engine zur Erkennung von Anomalien innerhalb dieser Zeit eine Bewertung für die Anwendung und gibt sie zurück.



*Verwandte Informationen*

link:assigning-applications-to-assets.md#["Zuweisen von Anwendungen zu Assets"]
