---
permalink: config-admin/copying-table-values.html 
sidebar: sidebar 
keywords:  
summary: Sie können Werte in Tabellen kopieren, um sie in Suchfeldern oder anderen Anwendungen zu verwenden. 
---
= Tabellenwerte werden kopiert
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können Werte in Tabellen kopieren, um sie in Suchfeldern oder anderen Anwendungen zu verwenden.



== Über diese Aufgabe

Es gibt zwei Methoden, mit denen Sie Werte aus Tabellen oder Abfrageergebnissen kopieren können.



== Schritte

. Methode 1: Markieren Sie den gewünschten Text mit der Maus, kopieren Sie ihn und fügen Sie ihn in Suchfelder oder andere Anwendungen ein.
. Methode 2: Bewegen Sie bei Einzelwertfeldern, deren Länge die Breite der Tabellenspalte überschreitet, die durch Ellipsen (...) gekennzeichnet sind, den Mauszeiger über das Feld und klicken Sie auf das Clipboard-Symbol. Der Wert wird zur Verwendung in Suchfeldern oder anderen Anwendungen in die Zwischenablage kopiert.
+
Beachten Sie, dass nur Werte, die Verknüpfungen zu Assets darstellen, kopiert werden können. Beachten Sie auch, dass nur Felder, die einzelne Werte enthalten (d. h. nicht-Listen), das Kopiersymbol haben.


