---
permalink: config-admin/emc-vnxe-data-source.html 
sidebar: sidebar 
keywords:  
summary: Die EMC VNXe Datenquelle bietet Bestandsunterstützung für EMC VNXe- und Unity Unified Storage-Arrays. 
---
= EMC VNXe -Datenquelle
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die EMC VNXe Datenquelle bietet Bestandsunterstützung für EMC VNXe- und Unity Unified Storage-Arrays.

Diese Datenquelle ist CLI-basiert und erfordert, dass Sie Unisphere for VNXe CLI (uemcli.exe) auf der Erfassungseinheit installieren, auf der sich die VNXe-Datenquelle befindet. uemcli.exe verwendet HTTPS als Transportprotokoll, daher muss die Erfassungseinheit in der Lage sein, HTTPS-Verbindungen zu den VNXe/Unity-Arrays zu initiieren. Sie müssen mindestens einen schreibgeschützten Benutzer zur Verwendung durch die Datenquelle haben.



== Terminologie

OnCommand Insight erfasst die folgenden Bestandsinformationen aus der EMC VNXe -Datenquelle. Für jeden von Insight erworbenen Asset-Typ wird die für dieses Asset am häufigsten verwendete Terminologie angezeigt. Beachten Sie bei der Anzeige oder Fehlerbehebung dieser Datenquelle die folgende Terminologie:

|===


| Anbieter-/Modelllaufzeit | Insight Laufzeit 


 a| 
Festplatte
 a| 
Festplatte



 a| 
Storage Array Durchführt
 a| 
Storage



 a| 
Prozessor
 a| 
Storage-Node



 a| 
Storage-Pool
 a| 
Storage-Pool



 a| 
Allgemeine iSCSI-Block-Informationen, VMware VMFS
 a| 
Datenmenge



 a| 
Freigegebener Ordner
 a| 
Internes Volumen



 a| 
CIFS-Freigabe, NFS-Freigabe, Freigabe vom VMware-NFS-Datastore
 a| 
Share



 a| 
Remote-Replikationssystem
 a| 
Synchronisierung



 a| 
ISCSI-Node
 a| 
ISCSI-Ziel-Node



 a| 
ISCSI-Initiator
 a| 
ISCSI-Target-Initiator

|===
[NOTE]
====
Es handelt sich dabei nur um gängige Terminologiezuordnungen, die für diese Datenquelle möglicherweise nicht alle Fälle darstellen.

====


== Anforderungen

Die folgenden Anforderungen gelten für die Konfiguration und Verwendung dieser Datenquelle:

* Der VNXe-Datensammler ist CLI-basiert. Sie müssen Unisphere for VNXe CLI (uemcli.exe) auf der Erfassungseinheit installieren, in der sich Ihr VNXe-Datensammler befindet.
* uemcli.exe verwendet HTTPS als Transportprotokoll, sodass die Erfassungseinheit in der Lage sein muss, HTTPS-Verbindungen zur VNXe zu initiieren.
* Sie müssen mindestens einen schreibgeschützten Benutzer zur Verwendung durch die Datenquelle haben.
* IP-Adresse des Managing Solutions Enabler Servers.
* HTTPS am Port 443 ist erforderlich
* Der EMC VNXe Data Collector bietet NAS- und iSCSI-Unterstützung für die Bestandsaufnahme. Fibre-Channel-Volumes werden erkannt, Insight jedoch keine Berichte über FC-Mapping, -Maskierung oder Speicherports.




== Konfiguration

|===


| Feld | Beschreibung 


 a| 
VNXe-Speicher
 a| 
IP-Adresse oder vollqualifizierter Domänenname des VNXe -Geräts



 a| 
Benutzername
 a| 
Benutzername für das VNXe-Gerät



 a| 
Passwort
 a| 
Kennwort für das VNXe -Gerät



 a| 
Vollständiger Pfad zur ausführbaren Datei uemcli
 a| 
Vollständiger Pfad zum `uemcli.exe` Ausführbar

|===


== Erweiterte Konfiguration

|===


| Feld | Beschreibung 


 a| 
Abfrageintervall für Bestand (min)
 a| 
Intervall zwischen Bestandsabstimmungen (Standard: 40 Minuten)



 a| 
VNXe-CLI-Port
 a| 
Port, der für die VNXe-CLI verwendet wird



 a| 
Zeitlimit für externen Prozess für Bestandsaufnahme (Sek.)
 a| 
Externes Prozess-Timeout (Standard: 1800 Sekunden)

|===