---
permalink: config-admin/examining-network-performance.html 
sidebar: sidebar 
keywords:  
summary: Sie können die Performance Ihrer Storage-Umgebung untersuchen und unzureichend ausgelastete und überlastete Ressourcen identifizieren und Risiken identifizieren, bevor diese zu Problemen werden. 
---
= Überprüfung der Netzwerkleistung
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die Performance Ihrer Storage-Umgebung untersuchen und unzureichend ausgelastete und überlastete Ressourcen identifizieren und Risiken identifizieren, bevor diese zu Problemen werden.

Mithilfe von Insight können Sie Performance- und Verfügbarkeitsprobleme beheben und verhindern, die durch die erfassten Storage-Daten verursacht werden.

Sie können Insight verwenden, um die folgenden Aufgaben zum Performance-Management durchzuführen:

* Überwachung der Performance in der gesamten Umgebung
* Ermittlung von Ressourcen, die die Leistung anderer Geräte beeinflussen




== Die Bedeutung von Ports

Für den Insight Server und den Data Warehouse (DWH)-Server müssen möglicherweise mehrere TCP-Ports frei sein, um zuverlässig arbeiten zu können. Einige dieser Ports werden nur für Prozesse verwendet, die an den localhost-Adapter gebunden sind (127.0.0.1), aber dennoch benötigt werden, damit die Kerndienste zuverlässig arbeiten können. Die Anzahl der erforderlichen Ports ist eine Überzahl der Ports, die im gesamten Netzwerk verwendet werden.



== Insight Server-Ports

Für Insight Server können Software-Firewalls installiert sein. Die "Löcher", die geöffnet werden müssten, wären wie unten beschrieben.

*Inbound HTTPS 443* - vorausgesetzt, Sie haben die Insight WebUI auf TCP 443 ausgeführt, müssen Sie das als, um alle und alle der folgenden Verbraucher zu ermöglichen offenlegen:

* Insight Benutzer der WebUI
* Remote-Erfassungseinheiten, die eine Verbindung zum Insight-Server herstellen möchten
* OCI DWH-Server mit Verbindungen zu diesem Insight-Server.
* Programmatische Interaktionen mit der Insight REST-API


Unsere allgemeine Empfehlung für alle, die eine Firewall auf Insight Server-Ebene implementieren möchten, ist der HTTPS-Zugriff auf alle IP-Blöcke des Unternehmensnetzwerks.

*Inbound MySQL (TCP 3306)*. Dieser Port muss nur jedem Insight DWH-Server mit einem Konnektor zugänglich sein

Während Insight Dutzende von Datensammlern umfasst, sind sie alle Umfragebasiert – Insight wird dazu führen, dass seine Acquisition Units (aus) ausgehende Kommunikation mit verschiedenen Geräten initiieren. Solange Ihre hostbasierte Firewall „statusorientiert“ ist, sodass sie Rückverkehr über die Firewall zulässt, sollten hostbasierte Firewalls auf dem Insight Server die Datenerfassung nicht beeinträchtigen.



== Data Warehouse-Ports

Für Insight DWH-Server:

*Inbound HTTPS 443* - vorausgesetzt, Sie haben die Insight WebUI läuft auf TCP 443, müssen Sie das als die folgenden Verbraucher zu ermöglichen:

* Insight administrative Benutzer des DWH Admin-Portals


*Inbound HTTPS (TCP 9300)* - das ist die Cognos Reporting-Schnittstelle. Wenn Benutzer mit der Cognos-Reporting-Schnittstelle interagieren, muss diese Remote angezeigt werden.

Wir können uns Umgebungen vorstellen, in denen das DWH möglicherweise nicht offengelegt werden muss - vielleicht stellen die Verfasser des Berichts einfach RDP-Verbindungen zum DWH-Server her und erstellen und planen dort Berichte, während alle Berichte über SMTP geliefert oder auf ein Remote-Dateisystem geschrieben werden sollen.

*Inbound MySQL (TCP 3306)*. Dieser Port muss nur dann offengelegt werden, wenn Ihr Unternehmen MySQL-basierte Integrationen mit DWH-Daten hat. Extrahieren Sie Daten aus den verschiedenen DWH-Data Marts zur Aufnahme in andere Anwendungen wie CMDBs, Chargeback-Systeme usw.
