---
permalink: config-admin/ibm-xiv-cli-data-source.html 
sidebar: sidebar 
keywords:  
summary: 'Die IBM XIV \(CLI\)-Datenquelle wird über die XIV-Befehlszeilenschnittstelle inventarisiert. Die XIV-Leistung wird durch SMI-S-Aufrufe an das XIV-Array erreicht, das einen SMI-S-Provider auf Port 5989 ausführt.' 
---
= IBM XIV-Datenquelle
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die IBM XIV (CLI)-Datenquelle wird über die XIV-Befehlszeilenschnittstelle inventarisiert. Die XIV-Leistung wird durch SMI-S-Aufrufe an das XIV-Array erreicht, das einen SMI-S-Provider auf Port 5989 ausführt.



== Terminologie

OnCommand Insight erwirbt die folgenden Inventarinformationen aus der IBM XIV-Datenquelle. Für jeden von Insight erworbenen Asset-Typ wird die für dieses Asset am häufigsten verwendete Terminologie angezeigt. Beachten Sie bei der Anzeige oder Fehlerbehebung dieser Datenquelle die folgende Terminologie:

|===


| Anbieter-/Modelllaufzeit | Insight Laufzeit 


 a| 
Festplatte
 a| 
Festplatte



 a| 
Storage-System
 a| 
Storage



 a| 
Storage-Pool
 a| 
Storage-Pool



 a| 
Datenmenge
 a| 
Datenmenge

|===
[NOTE]
====
Es handelt sich dabei nur um gängige Terminologiezuordnungen, die für diese Datenquelle möglicherweise nicht alle Fälle darstellen.

====


== Anforderungen

* Port-Anforderung: TCP-Port 7778
* IP-Adresse der XIV-Verwaltungsschnittstelle
* Schreibgeschützter Benutzername und Kennwort
* Die XIV CLI muss auf dem Insight Server oder der rau installiert sein
* Zugriffsvalidierung: Melden Sie sich über den Insight Server bei der XIV-Benutzeroberfläche mit Benutzername und Passwort an.




== Konfiguration

|===


| *Feld* | *Beschreibung* 


 a| 
IP-Adresse
 a| 
IP-Adresse oder vollständig qualifizierter Domänenname für den XIV-Speicher



 a| 
Benutzername
 a| 
Benutzername für den XIV Storage



 a| 
Passwort
 a| 
Passwort für den XIV-Speicher



 a| 
Vollständiger Pfad zum XIV CLI-Verzeichnis
 a| 
Vollständiger Pfad zum XIV CLI-Verzeichnis

|===


== Erweiterte Konfiguration

|===


| *Feld* | *Beschreibung* 


 a| 
Abfrageintervall für Bestand (min)
 a| 
Intervall zwischen Bestandsabstimmungen (Standard: 40 Minuten)



 a| 
Zeitüberschreitung bei CLI-Prozess (ms)
 a| 
CLI-Prozess-Timeout (Standard: 7200000 ms)



 a| 
SMI-S-HOST-IP
 a| 
IP-Adresse des SMI-S Provider-Hosts



 a| 
SMI-S-Port
 a| 
Vom SMI-S Provider-Host verwendeter Port



 a| 
SMI-S-Protokoll
 a| 
Protokoll für die Verbindung mit dem SMI-S-Provider



 a| 
SMI-S Namespace
 a| 
SMI-S Namespace



 a| 
Benutzername
 a| 
Benutzername für den SMI-S Provider Host



 a| 
Passwort
 a| 
Kennwort für den SMI-S Provider-Host



 a| 
Leistungsintervall (Sek.)
 a| 
Intervall zwischen Performance-Abstimmungen (standardmäßig 300 Sekunden)



 a| 
Anzahl der erneuten SMI-S-Verbindungsversuche
 a| 
Anzahl der Wiederholungsversuche für SMI-S-Verbindungen

|===