---
permalink: config-admin/listing-installed-oncommand-insight-packages.html 
sidebar: sidebar 
keywords:  
summary: Sie können eine Liste der installierten OnCommand Insight-Komponenten anzeigen, darunter unter anderem Inventar, Kapazität, Abmessungen, Und die Data Warehouse-Ansichten. Der Customer Support fragt Sie möglicherweise nach diesen Informationen, oder Sie möchten vielleicht sehen, welche Softwareversionen installiert wurden und wann sie installiert wurden. 
---
= Auflisten der installierten OnCommand Insight-Komponenten
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können eine Liste der installierten OnCommand Insight-Komponenten anzeigen, darunter unter anderem Inventar, Kapazität, Abmessungen, Und die Data Warehouse-Ansichten. Der Customer Support fragt Sie möglicherweise nach diesen Informationen, oder Sie möchten vielleicht sehen, welche Softwareversionen installiert wurden und wann sie installiert wurden.



== Schritte

. Klicken Sie in der Insight-Symbolleiste auf *Admin* und wählen Sie *Fehlerbehebung*.
. Klicken Sie unten auf der Seite im Bereich Weitere Aufgaben auf den Link *Erweiterte Fehlerbehebung*.
. Klicken Sie auf der Seite Erweiterte Fehlerbehebung auf die Registerkarte *Reports*.
. Klicken Sie Auf *Installierte Softwarepakete*.

