---
permalink: config-admin/managing-security-on-an-rau.html 
sidebar: sidebar 
keywords: rekey 
summary: Mit dem Tool securityadmin können Sie die Sicherheitsoptionen auf raus verwalten. Möglicherweise müssen Sie eine Vault-Konfiguration sichern oder wiederherstellen, Verschlüsselungsschlüssel ändern oder Kennwörter für die Erfassungseinheiten aktualisieren. 
---
= Verwaltung der Sicherheit auf einer rau
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der `securityadmin` Mit dem Tool können Sie Sicherheitsoptionen auf raus verwalten. Möglicherweise müssen Sie eine Vault-Konfiguration sichern oder wiederherstellen, Verschlüsselungsschlüssel ändern oder Kennwörter für die Erfassungseinheiten aktualisieren.



== Über diese Aufgabe

Sie verwenden das `securityadmin` Tool zur Verwaltung der Sicherheit:

* Fenster – `C:\Program Files\SANscreen\securityadmin\bin\securityadmin.bat`
* Linux `/bin/oci-securityadmin.sh`


Ein Szenario für die Aktualisierung der Sicherheitskonfiguration für die LAU/rau ist die Aktualisierung des Benutzerpassworts für die Erfassung, wenn das Kennwort für diesen Benutzer auf dem Server geändert wurde. Die LAU und alle raus verwenden das gleiche Passwort wie das des Benutzer „Acquisition“ des Servers, um mit dem Server zu kommunizieren.

Der Benutzer „Acquisition“ ist nur auf dem Insight-Server vorhanden. Die rau oder LAU melden sich als dieser Benutzer an, wenn sie eine Verbindung zum Server herstellen.

Weitere Informationen finden Sie in den link:../config-admin\/security-management.html["Sicherheitstool"] Anweisungen.
