---
permalink: config-admin/managing-security-on-the-local-acquisition-unit.html 
sidebar: sidebar 
keywords:  
summary: 'Mit dem Tool securityadmin können Sie Sicherheitsoptionen auf dem lokalen Erfassungsbenutzer \(LAU\) verwalten. Die Sicherheitsverwaltung umfasst das Verwalten von Schlüsseln und Passwörtern, das Speichern und Wiederherstellen von Sicherheitskonfigurationen, die Sie erstellen oder auf die Standardeinstellungen wiederherstellen.' 
---
= Verwaltung der Sicherheit auf der lokalen Erfassungseinheit
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der `securityadmin` Mit dem Tool können Sie Sicherheitsoptionen für den lokalen Akquisitionsbenutzer (LAU) verwalten. Die Sicherheitsverwaltung umfasst das Verwalten von Schlüsseln und Passwörtern, das Speichern und Wiederherstellen von Sicherheitskonfigurationen, die Sie erstellen oder auf die Standardeinstellungen wiederherstellen.



== Bevor Sie beginnen

Dieser muss unbedingt vorhanden sein `admin` Berechtigungen zum Ausführen von Sicherheitskonfigurationsaufgaben.



== Über diese Aufgabe

Sie verwenden das `securityadmin` Tool zur Verwaltung der Sicherheit:

* Fenster – `C:\Program Files\SANscreen\securityadmin\bin\securityadmin.bat`
* Linux `/bin/oci-securityadmin.sh`




== Schritte

. Führen Sie eine Remote-Anmeldung beim Insight-Server durch.
. Starten Sie das Sicherheitsadministrator-Tool im interaktiven Modus (-i).
+
Das System fordert Anmeldeinformationen an.

. Geben Sie den Benutzernamen und das Kennwort für ein Konto mit „`Admin`“-Anmeldeinformationen ein.
. Wählen Sie *Local Acquisition Unit* aus, um die Sicherheitskonfiguration der Local Acquisition Unit neu zu konfigurieren.
+
Folgende Optionen werden angezeigt:

+
** *Backup*
+
Erstellt eine Sicherungszip-Datei des Tresors, die alle Passwörter und Schlüssel enthält und legt die Datei an einem vom Benutzer angegebenen Speicherort oder an den folgenden Standardstandorten ab:

+
*** Fenster – `C:\Program Files\SANscreen\backup\vault`
*** Linux `/var/log/netapp/oci/backup/vault`


** *Wiederherstellen*
+
Stellt die Zip-Sicherung des erstellten Tresors wieder her. Nach der Wiederherstellung werden alle Passwörter und Schlüssel zum Zeitpunkt der Backup-Erstellung auf die vorhandenen Werte zurückgesetzt.

+
[NOTE]
====
Restore kann verwendet werden, um Passwörter und Schlüssel auf mehreren Servern zu synchronisieren, zum Beispiel: - Verschlüsselungsschlüssel auf DEM LAU ändern - Erstellen einer Sicherung des Tresors - Wiederherstellen der Vault-Sicherung auf jedem der Raus

+

====
** *Verschlüsselungsschlüssel Ändern*
+
Ändern Sie die AU-Verschlüsselungsschlüssel, die zum Verschlüsseln oder Entschlüsseln von Gerätepasswörtern verwendet werden.

+
[NOTE]
====
Wenn Sie die Verschlüsselungsschlüssel ändern, sollten Sie Ihre neue Sicherheitskonfiguration sichern, damit Sie sie nach einem Upgrade oder einer Installation wiederherstellen können.

====
** *Passwort Aktualisieren*
+
Passwort für 'Acquisition'-Benutzerkonto ändern.

+
[NOTE]
====
Einige Konten müssen synchronisiert werden, wenn Passwörter geändert werden. Wenn Sie beispielsweise das Passwort für den Benutzer „Acquisition“ auf dem Server ändern, müssen Sie das Kennwort für den Benutzer „Acquisition“ auf DER LAU, rau und DWH ändern, damit es übereinstimmt. Wenn Sie Kennwörter ändern, sollten Sie außerdem Ihre neue Sicherheitskonfiguration sichern, damit Sie sie nach einem Upgrade oder einer Installation wiederherstellen können.

====
** *Auf die Standardeinstellungen zurücksetzen*
+
Setzt das Erfassungs-Benutzerpasswort und die Erfassungs-Benutzerverschlüsselungsschlüssel auf die Standardwerte zurück. Bei der Installation werden die Standardwerte angegeben.

** *Ausgang*
+
Beenden Sie das `securityadmin` Werkzeug.



. Wählen Sie die Option aus, die Sie konfigurieren möchten, und befolgen Sie die Anweisungen.

