---
permalink: config-admin/managing-security-on-the-insight-server.html 
sidebar: sidebar 
keywords:  
summary: Mit dem Tool securityadmin können Sie Sicherheitsoptionen auf dem Insight-Server verwalten. Die Sicherheitsverwaltung umfasst das Ändern von Kennwörtern, das Generieren neuer Schlüssel, das Speichern und Wiederherstellen von von von von Ihnen erstellten Sicherheitskonfigurationen oder das Wiederherstellen von Konfigurationen auf die Standardeinstellungen. 
---
= Sicherheitsmanagement auf dem Insight-Server
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der `securityadmin` Mit dem Tool können Sie Sicherheitsoptionen auf dem Insight-Server verwalten. Die Sicherheitsverwaltung umfasst das Ändern von Kennwörtern, das Generieren neuer Schlüssel, das Speichern und Wiederherstellen von von von von Ihnen erstellten Sicherheitskonfigurationen oder das Wiederherstellen von Konfigurationen auf die Standardeinstellungen.



== Über diese Aufgabe

Sie verwenden das `securityadmin` Tool zur Verwaltung der Sicherheit:

* Fenster – `C:\Program Files\SANscreen\securityadmin\bin\securityadmin.bat`
* Linux `/bin/oci-securityadmin.sh`


Weitere Informationen finden Sie in der link:../config-admin/securityadmin-tool.html["Sicherheitsadministration"] Dokumentation.
