---
permalink: config-admin/netapp-clustered-data-ontap-data-source.html 
sidebar: sidebar 
keywords:  
summary: Diese Datenquelle sollte für Storage-Systeme mit Clustered Data ONTAP verwendet werden. Sie erfordert ein Administratorkonto, das für schreibgeschützte API-Aufrufe verwendet wird. 
---
= Datenquelle von NetApp Clustered Data ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Diese Datenquelle sollte für Storage-Systeme mit Clustered Data ONTAP verwendet werden. Sie erfordert ein Administratorkonto, das für schreibgeschützte API-Aufrufe verwendet wird.



== Terminologie

OnCommand Insight erfasst die folgenden Inventarinformationen aus der Datenquelle von Clustered Data ONTAP. Für jeden von Insight erworbenen Asset-Typ wird die für dieses Asset am häufigsten verwendete Terminologie angezeigt. Beachten Sie bei der Anzeige oder Fehlerbehebung dieser Datenquelle die folgende Terminologie:

|===


| Anbieter-/Modelllaufzeit | Insight Laufzeit 


 a| 
Festplatte
 a| 
Festplatte



 a| 
Raid-Gruppe
 a| 
Festplattengruppe



 a| 
Cluster
 a| 
Storage



 a| 
Knoten
 a| 
Storage-Node



 a| 
Aggregat
 a| 
Storage-Pool



 a| 
LUN
 a| 
Datenmenge



 a| 
Datenmenge
 a| 
Internes Volumen

|===
[NOTE]
====
Es handelt sich dabei nur um gängige Terminologiezuordnungen, die für diese Datenquelle möglicherweise nicht alle Fälle darstellen.

====


== Anforderungen

* Administratorkonto wird für schreibgeschützte API-Aufrufe verwendet
* Ziel-IP ist die LIF zum Cluster-Management
* Benutzername (mit schreibgeschütztem Rollenname zur ontapi-Applikation auf dem Standard-Vserver) und Passwort zur Anmeldung beim NetApp Cluster
* Port-Anforderungen: 80 oder 443
* Lizenzanforderungen: FCP-Lizenz und zugeordnete/maskierte Volumes, die für die Erkennung erforderlich sind




== Konfiguration

|===


| *Feld* | *Beschreibung* 


 a| 
NetApp Management IP
 a| 
IP-Adresse oder vollqualifizierter Domain-Name des NetApp Clusters



 a| 
Benutzername
 a| 
Benutzername für das NetApp Cluster



 a| 
Passwort
 a| 
Passwort für den NetApp Cluster

|===


== Erweiterte Konfiguration

|===


| *Feld* | *Beschreibung* 


 a| 
Abfrageintervall für Bestand (min)
 a| 
Intervall zwischen Bestandsabstimmungen (Standard: 20 Minuten)



 a| 
Leistungsintervall (Sek.)
 a| 
Intervall zwischen Performance-Abstimmungen (standardmäßig 300 Sekunden)

|===