---
permalink: config-admin/using-options-in-the-preferences-tab.html 
sidebar: sidebar 
keywords:  
summary: Auf der Registerkarte „Voreinstellungen für die Geräteauflösung“ können Sie einen Zeitplan für die automatische Auflösung erstellen, Speicher- und Bandanbieter angeben, die die Identifizierung einschließen oder ausschließen sollen, und DNS-Suchoptionen festlegen. 
---
= Einstellungen auf der Registerkarte Einstellungen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Auf der Registerkarte „Voreinstellungen für die Geräteauflösung“ können Sie einen Zeitplan für die automatische Auflösung erstellen, Speicher- und Bandanbieter angeben, die die Identifizierung einschließen oder ausschließen sollen, und DNS-Suchoptionen festlegen.



== Zeitplan für die automatische Auflösung

Ein Zeitplan für die automatische Auflösung kann festlegen, wann die automatische Gerätelaufauflösung ausgeführt wird:

|===


| Option | Beschreibung 


 a| 
Alle
 a| 
Verwenden Sie diese Option, um die automatische Geräteauflösung in Intervallen von Tagen, Stunden oder Minuten durchzuführen.



 a| 
Jeden Tag
 a| 
Verwenden Sie diese Option, um die automatische Geräteauflösung täglich zu einem bestimmten Zeitpunkt auszuführen.



 a| 
Manuell
 a| 
Verwenden Sie diese Option, um nur die automatische Geräteauflösung manuell auszuführen.



 a| 
Bei jeder Umgebungsänderung
 a| 
Verwenden Sie diese Option, um bei jeder Änderung der Umgebung eine automatische Geräteauflösung auszuführen.

|===
Wenn Sie manuell angeben, wird die automatische Geräteauflösung nachts deaktiviert.



== DNS-Verarbeitungsoptionen

Mit den DNS-Verarbeitungsoptionen können Sie die folgenden Funktionen auswählen:

* Wenn die Verarbeitung der DNS-Suchtresultat aktiviert ist, können Sie eine Liste von DNS-Namen hinzufügen, die an aufgelöste Geräte angehängt werden sollen.
* Sie können „`Automatische Auflösung von IPs:`“ auswählen, um die automatische Hostauflösung für iSCSI-Initiatoren und Hosts zu aktivieren, die auf NFS-Freigaben über DNS Lookup zugreifen. Wenn dies nicht angegeben wird, wird nur FC-basierte Auflösung ausgeführt.
* Sie können Unterstriche in Hostnamen zulassen und anstelle des Standard-Port-Alias in Results einen Alias „Connected to“ verwenden.




== Einschließlich oder mit Ausnahme bestimmter Storage- und Tape-Anbieter

Zur automatischen Lösung können Sie bestimmte Speicher- und Bandanbieter ein- oder ausschließen. Möglicherweise möchten Sie bestimmte Anbieter ausschließen, wenn Sie beispielsweise wissen, dass ein bestimmter Host zu einem veralteten Host wird und von Ihrer neuen Umgebung ausgeschlossen werden sollte. Sie können auch Anbieter, die Sie zuvor ausgeschlossen haben, erneut hinzufügen, möchten aber nicht mehr ausgeschlossen werden.

[NOTE]
====
Die Regeln für die Geräteauflösung für Bänder gelten nur für WWNs, wobei der Hersteller für diesen WWN in den Voreinstellungen des Herstellers auf *nur als Band enthalten* gesetzt ist.

====