---
permalink: config-admin/viewing-queries.html 
sidebar: sidebar 
keywords:  
summary: Sie können Ihre Abfragen anzeigen, um Ihre Assets zu überwachen und zu ändern, wie Ihre Abfragen die Daten zu Ihren Assets anzeigen. 
---
= Anzeigen von Abfragen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können Ihre Abfragen anzeigen, um Ihre Assets zu überwachen und zu ändern, wie Ihre Abfragen die Daten zu Ihren Assets anzeigen.



== Schritte

. Melden Sie sich bei der OnCommand Insight Web UI an.
. Klicken Sie auf *Abfragen* und wählen Sie *Alle Anfragen anzeigen*.
. Sie können die Anzeige von Abfragen mit einer der folgenden Methoden ändern:
+
** Sie können Text in das Feld *Filter* eingeben, um nach bestimmten Abfragen zu suchen.
** Sie können die Sortierreihenfolge der Spalten in der Tabelle der Abfragen durch Klicken auf den Pfeil in der Spaltenüberschrift auf aufsteigender (Aufwärtspfeil) oder absteigender (Abwärtspfeil) ändern.
** Wenn Sie die Größe einer Spalte ändern möchten, bewegen Sie den Mauszeiger über die Spaltenüberschrift, bis ein blauer Balken angezeigt wird. Legen Sie die Maus über die Leiste, und ziehen Sie sie nach rechts oder links.
** Um eine Spalte zu verschieben, klicken Sie auf die Spaltenüberschrift und ziehen Sie sie nach rechts oder links.
** Beachten Sie beim Durchblättern der Abfrageergebnisse, dass sich die Ergebnisse ändern können, wenn Insight Ihre Datenquellen automatisch abfragt. Dies kann dazu führen, dass einige Elemente fehlen oder einige Elemente in der Reihenfolge erscheinen, je nachdem, wie sie sortiert sind.



