---
permalink: config-admin/violin-memory-data-source.html 
sidebar: sidebar 
keywords:  
summary: 'Die Datenquelle des Violin 6000-Series Flash Memory Array \(HTTP\) erfasst Netzwerkinformationen für die Analyse und Validierung von Violin 6000-Series Flash-Speicher-Arrays.' 
---
= Datenquelle von Violin Flash Memory Array
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die Datenquelle des Flash Memory Array (HTTP) von Violin 6000-Series erfasst Netzwerkinformationen für die Analyse und Validierung von Flash-Speicher-Arrays der Violin 6000-Series.



== Terminologie

[NOTE]
====
Dieser Datensammler ist ab OnCommand Insight 7.3.11 nicht mehr verfügbar.

====
OnCommand Insight erfasst die folgenden Inventarinformationen aus der Datenquelle des Flash-Speicher-Arrays der Violin 6000-Serie. Für jeden von Insight erworbenen Asset-Typ wird die für dieses Asset am häufigsten verwendete Terminologie angezeigt. Beachten Sie bei der Anzeige oder Fehlerbehebung dieser Datenquelle die folgende Terminologie:

|===


| Anbieter-/Modelllaufzeit | Insight Laufzeit 


 a| 
Violin Intelligent Memory Module (VIMM)
 a| 
Festplatte



 a| 
Container
 a| 
Storage



 a| 
Speicher-Gateway
 a| 
Storage-Node



 a| 
LUN
 a| 
Datenmenge



 a| 
Initiator, Initiatorgruppe, Ziel
 a| 
Volume Map, Volume Mask

|===
[NOTE]
====
Es handelt sich dabei nur um gängige Terminologiezuordnungen, die für diese Datenquelle möglicherweise nicht alle Fälle darstellen.

====


== Anforderungen

* Sie benötigen einen schreibgeschützten Benutzernamen und ein Kennwort für den Speicher.
* Validieren Sie den Zugriff über einen Webbrowser unter Verwendung der Storage-IP-Adresse.




== Konfiguration

|===


| Feld | Beschreibung 


 a| 
IP-Adresse oder FQDN des Hauptgateways des Violin Memory Array
 a| 
IP-Adresse oder vollständig qualifizierter Domänenname des Haupt-Gateways des Violin Memory Array



 a| 
Benutzername
 a| 
Benutzername für das Haupt-Gateway des Violin Memory Array



 a| 
Passwort
 a| 
Passwort für das Haupt-Gateway des Violin Memory Array

|===


== Erweiterte Konfiguration

|===


| Feld | Beschreibung 


 a| 
Kommunikations-Port
 a| 
Port für die Kommunikation mit Violin Array



 a| 
HTTPS aktiviert
 a| 
Wählen Sie aus, um HTTPS zu verwenden



 a| 
Abfrageintervall für Bestand (min)
 a| 
Intervall zwischen Bestandsabstimmungen (Standard: 20 Minuten)



 a| 
Verbindungs-Timeout (Sek.)
 a| 
Verbindungs-Timeout (Standard: 60 Sekunden)



 a| 
Leistungsintervall (Sek.)
 a| 
Intervall zwischen Performance-Abstimmungen (standardmäßig 300 Sekunden)

|===