---
permalink: config-admin/vmware-vsphere-web-services-data-source.html 
sidebar: sidebar 
keywords:  
summary: 'Die Datenquelle VMware vSphere \(Web Services\) erfasst ESX-Hostinformationen und erfordert schreibgeschützte Berechtigungen für alle Objekte im Virtual Center.' 
---
= VMware vSphere Datenquelle
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die Datenquelle „VMware vSphere (Web Services)“ sammelt ESX-Host-Informationen und erfordert Berechtigungen für alle Objekte im Virtual Center.



== Terminologie

OnCommand Insight bezieht die folgenden Inventarinformationen aus der VMware vSphere-Datenquelle. Für jeden von Insight erworbenen Asset-Typ wird die für dieses Asset am häufigsten verwendete Terminologie angezeigt. Beachten Sie bei der Anzeige oder Fehlerbehebung dieser Datenquelle die folgende Terminologie:

|===


| Anbieter-/Modelllaufzeit | Insight Laufzeit 


 a| 
Virtuelles Laufwerk
 a| 
Festplatte



 a| 
Host
 a| 
Host



 a| 
Virtual Machine
 a| 
Virtual Machine



 a| 
Datastore
 a| 
Datastore



 a| 
LUN
 a| 
LUN



 a| 
Fibre Channel-Port
 a| 
Port

|===
[NOTE]
====
Es handelt sich dabei nur um gängige Terminologiezuordnungen, die für diese Datenquelle möglicherweise nicht alle Fälle darstellen.

====


== Anforderungen

* IP-Adresse des Virtual Center-Servers
* Schreibgeschützter Benutzername und Kennwort in Virtual Center
* Schreibgeschützte Berechtigungen für alle Objekte im Virtual Center.
* SDK-Zugriff auf dem Virtual Center-Server
* Port-Anforderungen: http-80 HTTPS-443
* Überprüfen Sie den Zugriff, indem Sie sich mit Ihrem Benutzernamen und Kennwort beim Virtual Center Client anmelden und überprüfen, ob das SDK aktiviert ist, indem Sie eingeben `telnet <vc_ip\> 443`.




== Konfiguration

|===
| *Feld* 


| *Beschreibung* 


 a| 
Virtual Center-Adresse



 a| 
Netzwerkadresse für den Virtual Center- oder vSphere-Server, angegeben als IP _(nnn.nnn.nnn.nnn_ Format)-Adresse oder als Hostname, der über DNS aufgelöst werden kann.



 a| 
Benutzername



 a| 
Benutzername für den VMware-Server.



 a| 
Passwort



 a| 
Kennwort für den VMware-Server.

|===


== Erweiterte Konfiguration

|===


| *Feld* | *Beschreibung* 


 a| 
Abfrageintervall für Bestand (min)
 a| 
Intervall zwischen Bestandsabstimmungen (Standard: 20 Minuten)



 a| 
Verbindungs-Timeout (ms)
 a| 
Verbindungs-Timeout (Standard: 60000 ms)



 a| 
Filtern von VMs nach
 a| 
Wählen Sie aus, wie VMs gefiltert werden sollen



 a| 
Wählen Sie „Ausschließen“ oder „Einschließen“, um eine Liste anzugeben
 a| 
Geben Sie an, ob die VM-Liste unten bei der Datenerfassung ein- oder ausgeschlossen werden soll



 a| 
Liste der zu filternden VMs (durch Komma getrennt oder durch Semikolon getrennt, wenn im Wert Komma verwendet wird)
 a| 
Kommagetrennte oder durch Semikolon getrennte Liste von VMs, die ein- oder vom Abruf ausgeschlossen werden sollen



 a| 
Anzahl der Wiederholungen für Anfragen an vCenter
 a| 
Anzahl der erneuten Versuche der vCenter-Anforderung



 a| 
Kommunikations-Port
 a| 
Für VMware-Server verwendeter Port



 a| 
Leistungsintervall (Sek.)
 a| 
Intervall zwischen Performance-Abstimmungen (standardmäßig 300 Sekunden)

|===