---
settings:
  name: OnCommand Insight
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: de-de,us-en,ja-jp,ko-kr,zh-cn,zh-tw,es-es,fr-fr,it-it
sidebar:
  entries:
  - title: OnCommand Insight Dok
    url: "/index.html"
  - section: relnotes
  - section: overview
  - section: install-linux
  - section: install-windows
  - section: config-admin
  - section: dwh
  - section: reporting
  - section: faq
  - section: howto
  - title: Data Collector Supportmatrix
    url: "/config-admin/reference_data_collector_support_matrix.html"
  - title: Rechtliche Hinweise
    url: "/legal-notices.html"
