---
permalink: reporting/which-report-answers-your-question.html 
sidebar: sidebar 
keywords:  
summary: OnCommand Insight enthält vordefinierte Berichte, die verschiedene allgemeine Berichtsanforderungen berücksichtigen und wichtige Einblicke bieten, die die Grundlage für fundierte Entscheidungen zur Storage-Infrastruktur bilden. 
---
= Verwenden von vordefinierten Berichten zur Beantwortung häufiger Fragen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
OnCommand Insight enthält vordefinierte Berichte, die verschiedene allgemeine Berichtsanforderungen berücksichtigen und wichtige Einblicke bieten, die die Grundlage für fundierte Entscheidungen zur Storage-Infrastruktur bilden.

Die folgenden vordefinierten Berichte sind unter *Team content* > *Reports* oder *Team content* > *Vendor Specific Reports* verfügbar.

Neuere Versionen von Berichten sind möglicherweise im NetApp Storage Automation Store verfügbar. Im Automation Store sollten Sie regelmäßig nach Berichten suchen.

* *AWS Cloud Cost Data*
+
Der Cloud-Kostenbericht bietet eine konsolidierte Ansicht aller Ressourcen, sodass Sie die Nutzung und die Kosten von Cloud- und On-Premises-Services nachverfolgen, analysieren und optimieren können. Außerdem können Sie sie in Ihrer Umgebung dynamisch skalieren.

+
Der Bericht korreliert Kosten zwischen der Infrastruktur und erstellt eindeutige und verwertbare Berichte, um mittels gezielter Kapazitätsplanung und Abfallentsorgung das richtige Sizing zu gewährleisten.

* *Kapazität und Performance des Anwendungs-Service-Levels*
+
Der Bericht Application Service Level Capacity and Performance liefert einen allgemeinen Überblick über die Applikationen. Diese Informationen können für die Kapazitätsplanung oder für einen Migrationsplan verwendet werden.

* *Rückbelastung*
+
Der Bericht Chargeback liefert Informationen zur Rückberechnung von Storage-Kapazitäten nach Hosts, Applikationen und Geschäftseinheiten und schließt sowohl aktuelle als auch historische Daten ein.

+
Um zu verhindern, dass die Doppelzählung keine ESX Server beinhaltet, überwachen Sie nur die VMs.

+
Eine aktualisierte Version dieses Berichts finden Sie im NetApp Storage Automation Store.

* *Datenquellen*
+
Der Bericht „Datenquellen“ zeigt alle Datenquellen an, die auf Ihrem Standort installiert sind, den Status der Datenquelle (Erfolg/Fehler) und Statusmeldungen. Der Bericht enthält Informationen darüber, wo mit der Fehlerbehebung von Datenquellen begonnen werden soll. Fehlerhafte Datenquellen wirken sich auf die Genauigkeit von Insight-Berichten und die allgemeine Benutzerfreundlichkeit des Produkts aus.

* *ESX vs. VM-Performance*
+
Der Bericht ESX vs VM Performance zeigt einen Vergleich der ESX Server und VMs und zeigt die durchschnittliche und Spitzen-IOPS, den Durchsatz und die Latenz sowie die Auslastungen für ESX-Server und VMs an. Um eine Doppelzählung zu verhindern, schließen Sie die ESX Server aus; schließen Sie nur die VMs ein.

+
Eine aktualisierte Version dieses Berichts finden Sie im NetApp Storage Automation Store.

* *Stoff Zusammenfassung*
+
Der Bericht Fabric Summary identifiziert Switches und Switch-Informationen, einschließlich der Anzahl von Ports, Firmware-Versionen und Lizenzstatus. Der Bericht enthält keine NPV Switch-Ports.

* *Host-HBAs*
+
Der Bericht Host HBAs bietet einen Überblick über die Hosts in der Umgebung und bietet die Hersteller-, Modell- und Firmware-Version von HBAs sowie die Firmware-Ebene der Switches, mit denen sie verbunden sind. Dieser Bericht kann zur Analyse der Firmware-Kompatibilität bei der Planung eines Firmware-Upgrades für einen Switch oder einen HBA verwendet werden.

* *Kapazität und Leistung des Host Service Levels*
+
Der Bericht über Kapazität und Performance auf Host Service Level bietet einen Überblick über die Storage-Auslastung je Host für rein Block-beschränkte Applikationen.

* *Host Zusammenfassung*
+
Der Host Summary Report bietet einen Überblick über die Speichernutzung für jeden ausgewählten Host mit Informationen für Fibre Channel- und iSCSI-Hosts. Der Bericht ermöglicht den Vergleich von Ports und Pfaden, der Fibre Channel- und ISCSI-Kapazität und der Anzahl der Verstöße.

* *Lizenzdetails*
+
Im Bericht Lizenzdetails wird die berechtigte Menge an Ressourcen angezeigt, die Sie für alle Standorte mit aktiven Lizenzen lizenziert haben. Der Bericht zeigt außerdem eine Zusammenfassung der tatsächlichen Menge an allen Standorten mit aktiven Lizenzen. Die Zusammenfassung kann Überschneidungen von Storage Arrays umfassen, die von mehreren Servern gemanagt werden.

* *Mapped but not masked Volumes*
+
Der Bericht zugeordnete, jedoch nicht maskierte Volumes enthält die Volumes, deren Logical Unit Number (LUN) von einem bestimmten Host zur Verwendung zugeordnet wurde, jedoch nicht für diesen Host maskiert ist. In einigen Fällen können diese LUNs deaktiviert werden, die nicht maskiert wurden. Auf nicht maskierte Volumes kann jeder Host zugegriffen werden, wodurch sie anfällig für Datenkorruption sind.

* *NetApp Kapazität und Performance*
+
Der Bericht NetApp Capacity and Performance liefert globale Daten für zugewiesene, genutzte und zugeteilte Kapazitäten im Rahmen von Trend- und Performance-Daten zur NetApp Kapazität.

* *OCI Scorecard*
+
Der Bericht „OCI Scorecard“ bietet eine Zusammenfassung und einen allgemeinen Status aller von OnCommand Insight erkannten Assets. Der Status wird mit grünen, gelben und roten Markierungen angezeigt:

+
** Grün zeigt den normalen Zustand an
** Gelb zeigt ein potenzielles Problem in der Umgebung an
** Rot zeigt ein Problem an, das Aufmerksamkeit erfordert Alle Felder im Bericht werden im Datenwörterbuch beschrieben, das dem Bericht beiliegt.


* *Speicherzusammenfassung*
+
Der Bericht „Storage Summary“ bietet eine vollständige Übersicht über genutzte und nicht genutzte Kapazitätsdaten für Brutto-, zugewiesene Storage-Pools und Volumes. Dieser Bericht bietet einen Überblick über den gesamten erkannten Storage.

+
Eine neuere Version dieses Berichts finden Sie im NetApp Storage Automation Store.

* *VM Kapazität und Performance*
+
Beschreibt die VM-Umgebung (Virtual Machine) und ihre Kapazitätsauslastung. VM-Tools müssen aktiviert sein, um einige Daten anzuzeigen, z. B. wenn die VMs heruntergefahren wurden.

* *VM-Pfade*
+
Der Bericht zu VM-Pfaden enthält Daten zur Storage-Kapazität und Performancemetriken, wobei Virtual Machines auf welchem Host ausgeführt werden, welche Hosts auf welche gemeinsam genutzten Volumes zugreifen, was der aktive Zugriffspfad ist und welche Kapazitätszuweisung und -Nutzung umfasst.

* *HDS-Kapazität nach Thin Pool*
+
Der HDS Bericht zur Kapazität nach Thin Pool zeigt die Menge der nutzbaren Kapazität in einem Storage-Pool, der per Thin Provisioning bereitgestellt ist.

* *NetApp Kapazität nach Aggregat*
+
Der Bericht NetApp-Kapazität nach Aggregaten zeigt die Gesamtmenge, die Gesamtzahl der genutzten, verfügbaren und den engagierten Speicherplatz von Aggregaten.

* *Symmetrix-Kapazität durch Thick Array*
+
Der Bericht Symmetrix Capacity by Thick Array zeigt die Rohkapazität, nutzbare Kapazität, freie Kapazität, zugeordnet, maskiert, Und der gesamten freien Kapazität.

* *Symmetrix-Kapazität nach Thin Pool*
+
Der Bericht Symmetrix Capacity by Thin Pool zeigt die Rohkapazität, nutzbare Kapazität, genutzte Kapazität, freie Kapazität, verwendeter Prozentsatz, Abonnierte Kapazitäten und Abonnementtarif.

* *XIV Kapazität nach Array*
+
Der Bericht XIV Capacity by Array zeigt genutzte und ungenutzte Kapazität des Arrays an.

* *XIV Kapazität pro Pool*
+
Der Bericht zur Nutzung der XIV-Kapazität anhand von Pools zeigt genutzte und nicht genutzte Kapazität für Storage Pools an.


