---
permalink: install-windows/backing-up-the-security-configuration.html 
sidebar: sidebar 
keywords:  
summary: Wenn Ihre Insight-Komponenten eine nicht standardmäßige Sicherheitskonfiguration verwenden, müssen Sie die Sicherheitskonfiguration sichern und die Konfiguration anschließend auf allen Komponenten wiederherstellen, nachdem die neue Software installiert wurde. Die Sicherheitskonfiguration muss wiederhergestellt werden, bevor das Data Warehouse-Datenbankbackup wiederhergestellt wird. 
---
= Sichern der Sicherheitskonfiguration
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Ihre Insight-Komponenten eine nicht standardmäßige Sicherheitskonfiguration verwenden, müssen Sie die Sicherheitskonfiguration sichern und die Konfiguration anschließend auf allen Komponenten wiederherstellen, nachdem die neue Software installiert wurde. Die Sicherheitskonfiguration muss wiederhergestellt werden, bevor das Data Warehouse-Datenbankbackup wiederhergestellt wird.



== Über diese Aufgabe

Sie verwenden das `securityadmin` Tool zum Erstellen einer Sicherungskopie der Konfiguration und zum Wiederherstellen der gespeicherten Konfiguration. Weitere Informationen erhalten Sie, wenn Sie nach suchen `securityadmin` Im OnCommand Insight Dokumentationszentrum: http://docs.netapp.com/oci-73/index.jsp[]
