---
permalink: install-windows/insight-server-requirements.html 
sidebar: sidebar 
keywords: redhat 
summary: Es wird ein dedizierter Server empfohlen. Installieren Sie Insight nicht auf einem Server, auf dem andere Anwendungen installiert sind. Sowohl physische als auch virtuelle Server werden unterstützt, sofern die Produktanforderungen erfüllt sind. 
---
= Anforderungen für Insight Server
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es wird ein dedizierter Server empfohlen. Installieren Sie Insight nicht auf einem Server, auf dem andere Anwendungen installiert sind. Sowohl physische als auch virtuelle Server werden unterstützt, sofern die Produktanforderungen erfüllt sind.

Sie müssen über lokale Administratorberechtigungen verfügen, um die OnCommand Insight-Serversoftware installieren zu können.

[NOTE]
====
Die Dimensionierung für OnCommand Insight weist mehrere Abhängigkeiten auf, wie z. B. Art und Größe der Datenquelle, Anzahl der Assets in Ihrer Umgebung, Abfrageintervalle und mehr. Die folgenden Beispiele zur Größenbestimmung sind nur Richtlinien und stellen einige der Umgebungen dar, in denen Insight getestet wurde. Wenn sich diese oder andere Faktoren in der Umgebung ändern, können sich die Dimensionierungsanforderungen für Insight ändern. Diese Richtlinien enthalten Speicherplatz für Performance-Archivdaten von bis zu 90 Tagen.

====
Vor der Installation oder dem Upgrade der Insight sollten Sie sich an Ihren Sales Engineer wenden, um eine detaillierte Anleitung zur Größenbemessung zu erhalten.

*Beispiele:*

|===


| Umgebungsfaktoren: | Getesteter Festplattenspeicher, CPUs und Speicher: 


 a| 
80 Storage-Volume4.000

4,000 VMs

4,000 Switch-Ports
 a| 
250 GB Festplattenspeicherplatz 8 Kerne

32 GB RAM



 a| 
160 Storage-Volume40.000

8,000 VMs

8,000 Switch-Ports
 a| 
1 TB Festplattenspeicherplatz, 12 Kerne

48 GB RAM

|===
*Voraussetzungen:*

|===


| Komponente | Erforderlich 


 a| 
Betriebssystem
 a| 
Ein Computer, auf dem 64-Bit Microsoft Windows Server 2012, 2012 R2, 2016 oder 2019 mit dem neuesten Service Pack ausgeführt wird.

Das mit Windows Server 2012 eingeführte ausfallsichere Dateisystem (ReFS) ist nicht mit OnCommand Insight kompatibel. Die Windows-Installation von OnCommand Insight wird nur auf dem NTFS-Dateisystem unterstützt.

Es wird ein dedizierter Server empfohlen.



 a| 
Virtuelle Maschine (VM)
 a| 
Diese Komponente kann in einer virtuellen Umgebung ausgeführt werden, sofern die CPU- und Arbeitsspeicherressourcen für Ihre Instanz reserviert sind.



 a| 
Arbeitsspeicher und CPU
 a| 
24 BIS 256 GB RAM

8 - 32 Kerne

Es wird dringend empfohlen, die Größe der Auslagerungsdatei auf „`Windows Managed`“ zu setzen. Kleine Paging-Dateien fester Größe können die erfolgreiche Speicherung von Insight-Leistungsdaten beeinträchtigen.



 a| 
Verfügbarer Festplattenspeicher
 a| 
100 GB - 3 TB installiere Festplattenspeicher

50 GB - 1 TB Performance Archiv Speicherplatz

Für den Insight-Installationsbereich werden SSD-Festplatten empfohlen.



 a| 
Netzwerk
 a| 
Ethernet-Verbindung und -Ports:

* Ethernet-Verbindung mit 100 Mbit/s oder 1 Gbit/s mit dedizierter (statischer) IP-Adresse und IP-Konnektivität zu allen Komponenten im SAN, einschließlich FC-Geräten und Remote-Akquisitionseinheiten.
* Die Portanforderungen für den OnCommand Insight-Serverprozess sind 80, 443, 1090 bis 1100, 3873, 8083, 4444 bis 4446, 5445, 5455, 4712 bis 4714, 5500, Und 5501.
* Die Port-Anforderungen für den Akquisitionsprozess sind 12123 und 5679.
* Die Portanforderung für MySQL ist 3306.
* Die Portanforderungen für Elasticsearch lauten 9200 und 9310
* Die Anforderungen für dynamische Ports auf Win2008/2012 sind 49152 bis 65535


Die Ports 443 und 3306 erfordern externen Zugriff über jede vorhandene Firewall.



 a| 
Berechtigungen
 a| 
Lokale Administratorberechtigungen sind auf dem OnCommand Insight-Server erforderlich.

Wenn einer der folgenden Ordner symbolische Links sind, stellen Sie sicher, dass die Zielverzeichnisse über '755'-Berechtigungen verfügen.

* /Opt/netapp
* /Var/lib/netapp
* /Var/log/netapp




 a| 
Remote-Konnektivität
 a| 
Internetverbindung für den WebEx-Zugriff oder eine Remote-Desktop-Verbindung, um den Support bei der Installation und nach der Installation zu erleichtern.



 a| 
Zugänglichkeit
 a| 
HTTPS-Zugriff ist erforderlich.



 a| 
Virenscan
 a| 
Während der Installation dieser OnCommand Insight-Komponente müssen Sie alle Virenscanner vollständig deaktivieren. Nach der Installation müssen die von der Komponente Insight verwendeten Pfade (Installations-, Backup- und Archivierpfade) vom Virenscan ausgeschlossen werden.

Außerdem müssen Sie den IBM/DB2-Ordner (z. B. _C:\Program Files\IBM\DB2_) nach der Installation von der Virenprüfung ausschließen.



 a| 
HTTP- oder HTTPS-Server
 a| 
Microsoft Internetinformationsdienste (IIS) oder andere HTTPS-Server sollten nicht mit denselben Ports (443) konkurrieren wie der OnCommand Insight-Server und nicht automatisch starten. Wenn sie auf Port 443 hören müssen, müssen Sie den OnCommand Insight-Server so konfigurieren, dass andere Ports verwendet werden.

|===