---
permalink: install-windows/insight-java-ui-requirements.html 
sidebar: sidebar 
keywords:  
summary: Da der OnCommand InsightJava UI Client in einer Java-Laufzeitumgebung auf Ihrem Computer ausgeführt wird, ist es wichtig, dass Sie sicherstellen, dass Ihre Umgebung bestimmte Betriebssystem-, CPU- und Arbeitsspeicheranforderungen erfüllt. 
---
= Anforderungen an die Benutzeroberfläche von Insight Java
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Da der OnCommand InsightJava UI Client in einer Java-Laufzeitumgebung auf Ihrem Computer ausgeführt wird, ist es wichtig, dass Sie sicherstellen, dass Ihre Umgebung bestimmte Betriebssystem-, CPU- und Arbeitsspeicheranforderungen erfüllt.

Um auf den Java UI Client zuzugreifen, müssen Sie die Java-Laufzeitumgebung (JRE) auf Ihrem Computer installieren.

Für OnCommand Insight 7.3.2 und höher ist die 64-Bit-Version der Java Runtime Environment (JRE) erforderlich, um den Insight Java Client auszuführen.

|===


| Komponente | Anforderungen 


 a| 
Betriebssystem
 a| 
Alle Java 8-fähigen Maschinen. Der Java-basierte Client unterstützt Windows-, Macintosh- und Linux-Plattformen.



 a| 
CPU
 a| 
1.8 GHz oder schneller ist erforderlich.



 a| 
Speicher
 a| 
2 GB oder mehr werden empfohlen. Wenn Sie die Leistung von komplexen Rechenzentren überwachen (über 50,000 Switch-Ports), benötigt der Server mehr Speicher. Dies gilt nur, wenn die Lizenz Perform installiert ist.

|===