---
permalink: install-windows/installing-the-anomaly-detection-software.html 
sidebar: sidebar 
keywords:  
summary: OnCommand Insight enthält eine Software, die eine Anomalie von maschinellem Lernen auf Ihre Insight-Daten anwendet. Sie können diese Software separat von anderen OnCommand Insight-Komponenten installieren. 
---
= Installieren der Software zur Erkennung von Anomalien
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
OnCommand Insight enthält eine Software, die eine Anomalie von maschinellem Lernen auf Ihre Insight-Daten anwendet. Sie können diese Software separat von anderen OnCommand Insight-Komponenten installieren.



== Bevor Sie beginnen

Sie müssen alle Installationsvoraussetzungen erfüllt haben.



== Schritte

. Melden Sie sich beim Anomalieerkennungsserver mit einem Konto mit sudo-Berechtigungen an.
. Kopieren Sie die `.zip` Datei, die die Software zur Erkennung von Anomalien auf dem Linux-Server enthält.
. Extrahieren Sie die Dateien in den `oci-prelert-<version>-linux-x86_64` Verzeichnis.
. Navigieren Sie zu dem Verzeichnis, in dem sich das Installationsprogramm befindet: `cd oci-prelert-<version>-linux-x86_64`
. Installieren Sie die Software zur Erkennung von Anomalien: `sudo ./oci-prelert-install.sh`
+
Während der Installation werden Sie aufgefordert, den Servernamen oder die IP-Adresse des OnCommand Insight-Servers sowie den Benutzernamen und das Kennwort für ein Konto mit Administratorrechten einzugeben.

+
Sie können die Software zur Erkennung von Anomalien mit dem folgenden Befehl entfernen: `sudo /usr/bin/oci-prelert-uninstall.sh`





== Ergebnisse

Die Software wird automatisch mit der in der Installation angegebenen OnCommand Insight-Instanz registriert. Die Software kann nur mit der OnCommand Insight-Instanz kommunizieren, bei der sie registriert ist, und nur eine Instanz der Software kann bei einem OnCommand Insight-Server registriert werden.

Wenn Sie entweder den Server neu starten, auf dem die Anomalieerkennungssoftware ausgeführt wird, oder den Insight-Server, wird der Anomalieerkennungsprozess automatisch neu gestartet.

[NOTE]
====
Wenn Sie die Software zur Erkennung von Anomalien über die Befehlszeile mithilfe von Parametern installieren, kann sie sich nicht beim Insight-Server registrieren, es sei denn, Sie geben den folgenden Parameter an: `--path rest/v1`

====