---
permalink: install-windows/upgrading-data-warehouse.html 
sidebar: sidebar 
keywords:  
summary: Nachdem Sie alle erforderlichen Aufgaben abgeschlossen haben, können Sie sich beim Data Warehouse-Server anmelden und das Installationspaket ausführen, um das Upgrade abzuschließen. 
---
= Data Warehouse Wird Aktualisiert
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Nachdem Sie alle erforderlichen Aufgaben abgeschlossen haben, können Sie sich beim Data Warehouse-Server anmelden und das Installationspaket ausführen, um das Upgrade abzuschließen.



== Über diese Aufgabe

Inline-Upgrade wird vom Data Warehouse (DWH) nicht unterstützt. Führen Sie die folgenden Schritte aus, um auf die neue Version der DWH-Software zu aktualisieren.

[NOTE]
====
*Sie müssen den Tresor* sichern, bevor Sie das DWH-Upgrade durchführen.

Weitere Informationen finden Sie in den link:../config-admin\/security-management.html["Sicherheitstool"] Anweisungen.

====


== Schritte

Beim Aktualisieren des Data Warehouse müssen Sie die folgenden Aktionen ausführen:

. Stellen Sie nach der Installation von DWH 7.3.16 den Tresor und die Datenbank in der folgenden Reihenfolge wieder her:
+
.. Vault
.. Datenbank


. Melden Sie sich beim DWH-Server mit einem Konto an, das über lokale Windows-Administratorberechtigungen verfügt.
. Sichern Sie die DWH-DB und Berichte über die DWH-Portalschnittstelle.
. Sichern Sie den Vault. Siehe link:../config-admin/security-management.html["Sicherheitsadministration"]Dokumentation.
. Deinstallieren Sie die DWH-Software vom Server.
. Starten Sie den Server neu, um Komponenten aus dem Speicher zu entfernen.
. Installieren Sie die neue Version von DWH auf dem Server.
+
Die Installation dauert etwa 2 Stunden. Es empfiehlt sich, alle Standardeinstellungen ausgewählt zu lassen.

. Stellen Sie den Tresor auf dem DWH-Server wieder her.
. Stellen Sie die DWH-Datenbank auf dem Server wieder her.




== Nachdem Sie fertig sind

Nach dem Upgrade müssen Sie die Data Warehouse-Datenbank wiederherstellen, die so lange oder länger dauern kann wie das Upgrade.

[NOTE]
====
Während eines OnCommand Insight-Upgrades ist es nicht ungewöhnlich, dass ein Kunde zu einem anderen Insight-Server wechselt. Wenn Sie Ihren Insight-Server geändert haben, zeigen die vorhandenen Konnektoren nach der Wiederherstellung der Data Warehouse-Datenbank auf die vorherige Server-IP-Adresse oder den Hostnamen. Es empfiehlt sich, den Konnektor zu löschen und einen neuen zu erstellen, um mögliche Fehler zu vermeiden.

====