---
permalink: install-linux/anomaly-detection-requirements.html 
sidebar: sidebar 
keywords: redhat 
summary: Die Software zur Anomalieerkennung erfordert ein bestimmtes Betriebssystem, eine bestimmte Menge an Arbeitsspeicher, CPU-Kerne und Festplattenspeicher. Sie müssen bestimmte Anforderungen erfüllen, um die Software zur Erkennung von Anomalien erfolgreich zu installieren. 
---
= Anforderungen bei der Anomalieerkennung
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die Software zur Anomalieerkennung erfordert ein bestimmtes Betriebssystem, eine bestimmte Menge an Arbeitsspeicher, CPU-Kerne und Festplattenspeicher. Sie müssen bestimmte Anforderungen erfüllen, um die Software zur Erkennung von Anomalien erfolgreich zu installieren.

|===


| Komponente | Erforderlich 


 a| 
Betriebssystem
 a| 
Ein Computer, auf dem eine lizenzierte Version einer der folgenden Versionen ausgeführt wird, auf dem keine andere Software auf Anwendungsebene ausgeführt wird:

* Red Hat Enterprise Linux 7.3, 7.4, 7.5, 7.6, 7.7 7.8, 7.9, 8.1, 8.2, 8.3, 8.4, 8.5
* CentOS 7.5, 7.6, 7.7, 7.8, 7.9 CentOS 8-Stream
* Oracle Enterprise Linux 7.5, 7.6, 7.7, 7.8, 7.9 8.1, 8.2, 8.3, 8.4, 8.5
* SUSE Enterprise Linux 15.1, 15.2, 15.3
* OpenSUSE 15.1, 15.2, 15.3


Eine lizenzierte Version stellt sicher, dass die für die Installation erforderlichen Abhängigkeiten automatisch vom Betriebssystem aufgelöst werden.

Es wird ein dedizierter Server empfohlen.



 a| 
Virtuelle Maschine (VM)
 a| 
Die Anomalieerkennung kann in einer virtuellen Umgebung ausgeführt werden, sofern die CPU- und Arbeitsspeicherressourcen für Ihre Instanz reserviert sind.



 a| 
CPU und Speicher
 a| 
Ein 8-Kern. 64-GB-Speicherserver.



 a| 
Verfügbarer Festplattenspeicher
 a| 
Der Server benötigt 200 GB freien Festplattenspeicher, der wie folgt partitioniert wird:

* 150 GB Zoll `/var/lib`
* 25 GB Zoll `/var/log`
* 25 GB Zoll `/opt`


Für die Softwareinstallation ist folgender Festplattenspeicher erforderlich:

* 5 GB Zoll `/var/lib`
* 25 GB Zoll `/var/log`
* 25 GB Zoll `/opt`


Es ist eine Best Practice zu montieren ``/opt``Und Auf separaten Datenträgern aus dem Root-Dateisystem (`/`).



 a| 
Berechtigungen
 a| 
Für die Installation der Software zur Erkennung von Anomalien sind sudo-Berechtigungen erforderlich.



 a| 
Netzwerk
 a| 
Der Insight-Server, auf dem Sie die Software zur Erkennung von Anomalien installieren möchten, muss sich im selben Netzwerk oder zumindest am selben Standort oder Rechenzentrum befinden wie der Server, auf dem das Erkennungsmodul für Anomalien ausgeführt wird. Die Anomalieerkennungssoftware unterstützt keine Konfiguration in einem Wide-Area Network (WAN).

TCP-Ports 8080 und 9200 müssen auf der VM offen sein.



 a| 
Voraussetzungen
 a| 
Sie müssen über eine gültige Perform-Lizenz verfügen.Sie müssen über die IP-Adresse des Insight-Servers verfügen, auf dem Sie die Software zur Erkennung von Anomalien installieren möchten.

Sie müssen eine alternative Portnummer auf dem Insight-Server haben, wenn Sie den Standardport nicht akzeptieren.

TCP-Ports 8080 und 9200 müssen auf der VM offen sein.

Sie müssen über einen Benutzernamen und ein Kennwort für ein Konto mit Administratorrechten auf der VM verfügen.

Sie müssen zwei umgekehrte Schrägstriche (Firma\\Benutzer) für einen Benutzernamen eingeben, der einen einzelnen umgekehrten Schrägstrich enthält (Firma\Benutzer).

Ein Benutzername darf kein „`t`“ nach einem umgekehrten Schrägstrich (Firma\\tom) enthalten.

|===
[NOTE]
====
Sie müssen alle Empfehlungen zur Größenbestimmung mit einem NetApp Vertreter besprechen und validieren.

====