---
permalink: install-linux/installation-prerequisites.html 
sidebar: sidebar 
keywords:  
summary: Bevor Sie OnCommand Insight installieren, müssen Sie die aktuelle Softwareversion herunterladen, die entsprechende Lizenz erwerben und Ihre Umgebung einrichten. 
---
= Installationsvoraussetzungen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bevor Sie OnCommand Insight installieren, müssen Sie die aktuelle Softwareversion herunterladen, die entsprechende Lizenz erwerben und Ihre Umgebung einrichten.

Stellen Sie vor der Installation von OnCommand Insight sicher, dass folgende Informationen zur Verfügung stehen:

* OnCommand Insight-Softwaredateien im heruntergeladenen Installationspaket für die aktuelle Version
* Eine Lizenz zum Betrieb der heruntergeladenen OnCommand Insight-Version
* Minimale Hardware- und Softwareumgebung
+
Das aktuelle Produkt verbraucht möglicherweise zusätzliche Hardwareressourcen (aufgrund der erweiterten OnCommand Insight-Produktfunktionen), die bei früheren Versionen des OnCommand Insight Produkts nicht in Anspruch genommen wurden.

* Ein Bereitstellungsplan, der die Hardware- und Netzwerkkonfigurationen für den OnCommand Insight-Server, das Data Warehouse und die Berichterstellung sowie die Remote-Erfassungseinheiten umfasst.
* Java 8 für die Java-Benutzeroberfläche von OnCommand Insight.
+

NOTE: OnCommand Insight enthält eine kostenpflichtige Oracle-Lizenz für Java SE 8. Kunden müssen keine zusätzlichen Java SE 8 Lizenzen erwerben. Diese Lizenz deckt die Verwendung von Java SE 8 mit allen OCI-Komponenten ab. Weitere Informationen finden Sie im link:legal-notices.html["Mitteilungen"] Für spezifische Details.


