---
permalink: install-linux/uninstalling-an-ethernet-monitoring-unit-emu-linux.html 
sidebar: sidebar 
keywords:  
summary: Sie können eine Ethernet-Überwachungseinheit deinstallieren, wenn Sie sie nicht mehr benötigen. 
---
= Deinstallieren einer Ethernet-Überwachungseinheit
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können eine Ethernet-Überwachungseinheit deinstallieren, wenn Sie sie nicht mehr benötigen.



== Über diese Aufgabe

[NOTE]
====
Die Ethernet-Überwachungseinheit (EMU) wird in OnCommand Insight Version 7.3.12 und höher nicht unterstützt.

====


== Schritte

. Melden Sie sich beim Ethernet Monitoring Unit-Server mit einem Konto mit sudo-Berechtigungen an.
. Stellen Sie sicher, dass alle OnCommand Insight-Fenster geschlossen sind.
. Sie können Syntax, Befehlsargumente und Parameterverwendung für anzeigen `uninstall.sh` Indem Sie den folgenden Befehl eingeben: `sudo /usr/bin/oci-uninstall.sh --help`
. Geben Sie den folgenden Befehl ein: `sudo /usr/bin/oci-uninstall.sh`
+
Das Deinstallationsskript wird ausgeführt. Befolgen Sie alle Anweisungen.

. Starten Sie den Server nach Abschluss der Deinstallation neu.

