---
permalink: install-linux/upgrading-remote-acquisition-units.html 
sidebar: sidebar 
keywords:  
summary: Nach dem Upgrade der Insight Server-Software müssen Sie die Software für die Remote-Erfassung aktualisieren. 
---
= Aktualisierung der Remote Acquisition Unit-Software
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Nach dem Upgrade der Insight Server-Software müssen Sie die Software für die Remote-Erfassung aktualisieren.



== Schritte

. Melden Sie sich beim RAU-Server (Remote Acquisition Unit) mit einem Konto mit sudo-Berechtigungen an.
. Laden Sie die Insight rau Software von der NetApp Support-Website herunter.
. Navigieren Sie zum Download-Verzeichnis, und geben Sie den folgenden Befehl ein:
+
`unzip oci-rau-<version>-linux-x86_64.zip`

+
Stellen Sie sicher, dass Sie die korrekte Versionsnummer der Installationsdatei haben.

. Sie können Syntax, Befehlsargumente und Parameterverwendung für anzeigen `oci-install.sh` :
+
`sudo ./oci-rau-<version>-linux-x86_64/oci-install.sh --help`

. Führen Sie das Installationsskript aus:
+
`sudo ./oci-rau-<version>-linux-x86_64/oci-install.sh`

. Akzeptieren Sie die Lizenzvereinbarung, und befolgen Sie die Anweisungen.

