---
permalink: install-linux/upgrading-data-warehouse.html 
sidebar: sidebar 
keywords:  
summary: Nach dem Upgrade der Insight Server Software müssen Sie die Data Warehouse Software aktualisieren. 
---
= Aktualisieren der Data Warehouse-Software
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Nach dem Upgrade der Insight Server Software müssen Sie die Data Warehouse Software aktualisieren.



== Über diese Aufgabe

[NOTE]
====
Es wird dringend empfohlen, den Tresor und die Datenbank vor der Aktualisierung der DWH zu sichern.

Weitere Informationen zum Tresor finden link:../config-admin\/security-management.html["Sicherheitstool"]Sie in den Anweisungen.

====


== Schritte

. Melden Sie sich beim Data Warehouse (DWH)-Server mit einem Konto mit sudo-Berechtigungen an.
. Laden Sie die Insight DWH Software von der NetApp Support-Website herunter.
. Navigieren Sie zum Download-Verzeichnis, und geben Sie den folgenden Befehl ein:
+
`unzip oci-dwh-<version>-linux-x86_64.zip`

+
Stellen Sie sicher, dass Sie die korrekte Versionsnummer der Installationsdatei haben.

. Sie können Syntax, Befehlsargumente und Parameterverwendung für anzeigen `oci-install.sh` :
+
`sudo ./oci-dwh-<version>-linux-x86_64/oci-install.sh --help`

. Führen Sie das Installationsskript aus:
+
`sudo ./oci-dwh-<version>-linux-x86_64/oci-install.sh`

. Akzeptieren Sie die Lizenzvereinbarung, und befolgen Sie die Anweisungen.

