---
permalink: install-linux/upgrading-ethernet-monitoring-units.html 
sidebar: sidebar 
keywords:  
summary: Nach dem Upgrade der Insight Server-Software müssen Sie die ethernet-Überwachungssoftware aktualisieren. 
---
= Aktualisieren der Ethernet Monitoring Unit-Software
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Nach dem Upgrade der Insight Server-Software müssen Sie die ethernet-Überwachungssoftware aktualisieren.



== Über diese Aufgabe

[NOTE]
====
Die Ethernet-Überwachungseinheit (EMU) wird in OnCommand Insight Version 7.3.12 und höher nicht unterstützt.

====


== Schritte

. Melden Sie sich beim Ethernet Monitoring Unit (EMU)-Server mit einem Konto mit sudo-Berechtigungen an.
. Laden Sie die Insight EMU Software von der NetApp Support-Website herunter.
. Navigieren Sie zum Download-Verzeichnis, und geben Sie den folgenden Befehl ein:
+
`unzip oci-ethernet-<version>-linux-x86_64.zip`

+
Stellen Sie sicher, dass Sie die korrekte Versionsnummer der Installationsdatei haben.

. Sie können Syntax, Befehlsargumente und Parameterverwendung für anzeigen `oci-install.sh` :
+
`sudo ./oci-ethernet-<version>-linux-x86_64/oci-install.sh --help`

. Führen Sie das Installationsskript aus:
+
`sudo ./oci-ethernet-<version>-linux-x86_64/oci-install.sh`

. Akzeptieren Sie die Lizenzvereinbarung, und befolgen Sie die Anweisungen.

