---
permalink: install-linux/upgrading-insight-server-software.html 
sidebar: sidebar 
keywords:  
summary: Sie können nach der Anmeldung beim Server nach OnCommand Insight-Serveraktualisierungen suchen. 
---
= Upgrade der Insight Server Software
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können nach der Anmeldung beim Server nach OnCommand Insight-Serveraktualisierungen suchen.

[NOTE]
====
Es wird dringend empfohlen, den Vault und die Datenbank vor dem Upgrade von OnCommand Insight zu sichern.

Weitere Informationen zum Tresor finden link:../config-admin\/security-management.html["Sicherheitstool"]Sie in den Anweisungen.

====


== Schritte

. Klicken Sie in der Insight-Symbolleiste auf das Symbol *Hilfe*.
. Wählen Sie *nach Updates suchen*.
. Klicken Sie auf *OK*, wenn die `Version is up to date` Meldung wird angezeigt.
. Wenn eine neuere Version erkannt wird, klicken Sie im Meldungsfeld auf den Link *hier herunterladen*.
. Klicken Sie auf der Seite *Download* auf *Download*. Notieren Sie sich den Speicherort des Download-Verzeichnisses.
+
Sie können die neuere Version auch von der NetApp Support-Website herunterladen.

. Melden Sie sich beim Insight-Server mit einem Konto mit sudo-Berechtigungen an.
. Navigieren Sie zum Download-Verzeichnis, und geben Sie den folgenden Befehl ein:
+
`unzip oci-<version>-linux-x86_64.zip`

+
Stellen Sie sicher, dass Sie die korrekte Versionsnummer der Installationsdatei haben.

. Sie können Syntax, Befehlsargumente und Parameterverwendung für anzeigen `oci-install.sh` :
+
`sudo ./oci-<version>-linux-x86_64/oci-install.sh --help`

. Führen Sie das Installationsskript aus:
+
`sudo ./oci-<version>-linux-x86_64/oci-install.sh`

. Akzeptieren Sie die Lizenzvereinbarung, und befolgen Sie die Anweisungen.

