---
permalink: dwh/annotations.html 
sidebar: sidebar 
keywords:  
summary: Anmerkungen bieten eine Methode zum Definieren von Informationen, die sich auf Objekte in Ihrer Umgebung beziehen, und ermöglichen Ihnen dann, Objekte basierend auf der Anmerkung zu verfolgen. Beispielsweise können Sie Geräten in Ihrer Umgebung Gebäude- oder Bodennummernkommentare hinzufügen und anschließend eine Abfrage erstellen, die alle Geräte im ersten Stock eines Datacenters zurückgibt. 
---
= Was Sie mit Anmerkungen tun können
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Anmerkungen bieten eine Methode zum Definieren von Informationen, die sich auf Objekte in Ihrer Umgebung beziehen, und ermöglichen Ihnen dann, Objekte basierend auf der Anmerkung zu verfolgen. Beispielsweise können Sie Geräten in Ihrer Umgebung Gebäude- oder Bodennummernkommentare hinzufügen und anschließend eine Abfrage erstellen, die alle Geräte im ersten Stock eines Datacenters zurückgibt.

Darüber hinaus können Sie sich alle Geräte eines bestimmten Datacenters oder einer Geschäftseinheit ansehen und ermitteln, welche Geschäftseinheit den meisten Tier-1-Storage verwendet. Dazu weisen Sie dem Gerät über die Web-UI von OnCommand Insight eine Anmerkung zu Datacentern, Unternehmenseinheiten oder Ebenen zu. Anschließend können Sie ausgewählte benutzerdefinierte Anmerkungen aus OnCommand Insight in das Data Warehouse übertragen. Dies soll dazu führen, dass die dem Objekt zugewiesenen Anmerkungswerte in Ihren benutzerdefinierten Berichten angezeigt werden.

Sie können festlegen, welche benutzerdefinierten Anmerkungen an das Data Warehouse übertragen werden. Anmerkungen werden als zusätzliche Spalten zur Objekttabelle im Inventar und zur entsprechenden Dimensionstabelle in den Datentabellen hinzugefügt. Wenn Sie die Anmerkungen zu Ressourcen über die OnCommand Insight-Benutzeroberfläche aktualisieren und das nächste Data Warehouse-Build starten oder warten, werden die Ergebnisse in den folgenden Tabellen angezeigt:

* dwh_Inventory.annotation_value
* dwh_Inventory.Object_to_annotation


Um sicherzustellen, dass in OnCommand Insight eingegebene Anmerkungen in Data Warehouse enthalten sind, sind die folgenden wichtigen Prozesse erforderlich:

* Bevor Sie Anmerkungen in das Data Warehouse importieren, müssen Sie sicherstellen, dass sie in OnCommand Insight vorbereitet werden.
+
Dazu können Sie die Option *Troubleshooting* > *Aktualisierung von Anmerkungen für Data Warehouse* manuell ausführen oder bis zum nächsten geplanten transienten Datenlauf warten. Wenn Sie die Aktualisierung von Anmerkungen erzwingen, erzwingen Sie, dass der OnCommand Insight-Server die transienten Daten (z. B. Anmerkungswerte) berechnet und in Datenbanktabellen platziert, damit der Data Warehouse ETL-Prozess die Daten lesen kann. Die Aktualisierung der Beschriftungsdaten erfolgt automatisch alle 15 Minuten. Sie können sie jedoch häufiger ausführen.

* Anschließend importieren Sie Anmerkungen in Data Warehouse mithilfe der Option Data Warehouse **Anmerkungen**.
* Wenn Sie Anmerkungen in Berichte aufnehmen möchten, die Sie mithilfe der Berichterstellungs-Tools des OnCommand Insight Reporting Portals erstellen, müssen Sie das Metadatenmodell für die OnCommand Insight-Berichterstellung aktualisieren.


Wenn Sie ein Data Warehouse aktualisieren, wird der Job mit Anmerkungen während der Wiederherstellung der Datenbank automatisch ausgeführt. Der Anmerkungsjob wird auch automatisch ausgeführt, wenn WildFly gestartet wird.

[NOTE]
====
WildFly ist ein Anwendungsserver, auf dem der OnCommand Insight-Java-Code ausgeführt wird und sowohl für den OnCommand Insight-Server als auch für das Data Warehouse benötigt wird.

====