---
permalink: dwh/configuring-reporting-ldap.html 
sidebar: sidebar 
keywords:  
summary: Über das Data Warehouse-Portal kann der Administrator die LDAP-Nutzung für Data Warehouse und Reporting konfigurieren. 
---
= Konfigurieren von LDAP für die Berichterstellung
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Über das Data Warehouse-Portal kann der Administrator die LDAP-Nutzung für Data Warehouse und Reporting konfigurieren.



== Bevor Sie beginnen

Sie müssen sich bei Insight als Administrator anmelden, um diese Aufgabe auszuführen.

Für alle Secure Active Directory (d. h. LDAPS)-Benutzer müssen Sie den AD-Servernamen genau so verwenden, wie er im Zertifikat definiert ist. Sie können die IP-Adresse nicht für die sichere AD-Anmeldung verwenden.



== Schritte

. Melden Sie sich beim Data Warehouse Portal unter an `+https://hostname/dwh+`, Wo `hostname` Ist der Name des Systems, auf dem OnCommand Insight Data Warehouse installiert ist.
. Klicken Sie im Navigationsfenster auf der linken Seite auf *Benutzerverwaltung*.
. Klicken Sie auf *LDAP-Konfiguration*.
. Wählen Sie *LDAP aktivieren*, um die LDAP-Benutzerauthentifizierung und -Autorisierung zu starten.
. Nehmen Sie alle erforderlichen Änderungen vor, um LDAP zu konfigurieren.
+
Die meisten Felder enthalten Standardwerte. Die Standardeinstellungen sind für das Active Directory gültig.

+
** *Attribut des Hauptnamens des Benutzers*
+
Attribut, das jeden Benutzer im LDAP-Server identifiziert. Standard ist `userPrincipalName`, Die weltweit einzigartig ist. OnCommand Insight versucht, den Inhalt dieses Attributs mit dem oben angegebenen Benutzernamen abzugleichen.

** *Rollenattribut*
+
LDAP-Attribut, das die Passung des Benutzers innerhalb der angegebenen Gruppe identifiziert. Standard ist `memberOf`.

** *Mail-Attribut*
+
LDAP-Attribut, das die E-Mail-Adresse des Benutzers identifiziert. Standard ist `mail`. Dies ist nützlich, wenn Sie Berichte von OnCommand Insight abonnieren möchten. Insight erfasst die E-Mail-Adresse des Benutzers bei der ersten Anmeldung und sucht danach nicht mehr.

+
[NOTE]
====
Wenn sich die E-Mail-Adresse des Benutzers auf dem LDAP-Server ändert, müssen Sie sie in Insight aktualisieren.

====
** *Distinguished Name Attribut*
+
LDAP-Attribut, das den Distinguished Name des Benutzers identifiziert. Der Standardwert ist `distinguishedName`.

** *Empfehlung*
+
Gibt an, ob dem Pfad zu anderen Domänen folgen soll, wenn sich mehrere Domänen im Unternehmen befinden. Sie müssen immer die Standardeinstellung verwenden `follow` Einstellung.

** *Timeout*
+
Dauer der Wartezeit auf eine Antwort vom LDAP-Server vor der Zeitüberschreitung in Millisekunden. Der Standardwert ist 2,000, was in allen Fällen angemessen ist und nicht geändert werden sollte.

** *LDAP-Server*
+
Dies ist die IP-Adresse oder der DNS-Name zur Identifizierung des LDAP-Servers. Um einen bestimmten Port zu identifizieren, wobei `ldap-server-address` Ist der Name des LDAP-Servers. Sie können das folgende Format verwenden:

+
[listing]
----
ldap://ldap-server-address:port
----
+
Um den Standardport zu verwenden, können Sie das folgende Format verwenden:

+
[listing]
----
ldap://ldap-server-address
----
+
[NOTE]
====
 When entering multiple LDAP servers in this field, separate entries with a comma, and ensure that the correct port number is used in each entry.
+ um die LDAP-Zertifikate zu importieren, klicken Sie auf *Zertifikate importieren* und importieren bzw. suchen Sie die Zertifikatdateien manuell.

====
** *Domäne*
+
LDAP-Knoten, auf dem OnCommand Insight nach dem LDAP-Benutzer suchen soll. Dies ist in der Regel die Domäne der obersten Ebene für das Unternehmen. Beispiel:

+
[listing]
----
DC=<enterprise>,DC=com
----
** *Insight Server Admins-Gruppe*
+
LDAP-Gruppe für Benutzer mit Insight Server Administrator-Berechtigungen. Standard ist `insight.server.admins`.

** *Gruppe der Insight-Administratoren*
+
LDAP-Gruppe für Benutzer mit Insight Administrator-Berechtigungen. Standard ist `insight.admins`.

** *Insight Benutzergruppe*
+
LDAP-Gruppe für Benutzer mit Insight-Benutzerberechtigungen. Standard ist `insight.users`.

** *Insight Gästegruppe*
+
LDAP-Gruppe für Benutzer mit Insight Gastberechtigungen. Standard ist `insight.guests`.

** *Gruppe der Reporting-Administratoren*
+
LDAP-Gruppe für Benutzer mit Administratorrechten für Insight Reporting. Standard ist `insight.report.admins`.

** *Reporting pro Autorengruppe*
+
LDAP-Gruppe für Benutzer mit Insight Reporting Pro-Autorenrechten. Standard ist `insight.report.proauthors`.

** *Reporting Business Authors-Gruppe*
+
LDAP-Gruppe für Benutzer mit Berechtigungen für Business-Autoren von Insight Reporting. Standard ist `insight.report.business.authors`.

** *Gruppe der Geschäftskonsumenten melden*
+
LDAP-Gruppe für Benutzer mit Insight Reporting-Rechten für Geschäftskunden. Standard ist `insight.report.business.consumers`.

** *Empfängergruppe melden*
+
LDAP-Gruppe für Benutzer mit Insight Reporting-Empfängerberechtigungen. Standard ist `insight.report.recipients`.



. Geben Sie Werte in die Felder *Directory Lookup user* und *Directory Lookup user password* ein, wenn Sie Änderungen vorgenommen haben.
+
Wenn Sie die überarbeiteten Werte nicht in diese Felder eingeben, werden Ihre Änderungen nicht gespeichert.

. Geben Sie das Passwort für die Verzeichnissuche erneut in das Feld *Confirm Directory lookup user password* ein, und klicken Sie auf *Validate Password*, um das Passwort auf dem Server zu validieren.
. Klicken Sie auf *Update*, um die Änderungen zu speichern. Klicken Sie auf *Abbrechen*, um die Änderungen zu entfernen.

