---
permalink: howto/configuring-servicenow-for-integration.html 
sidebar: sidebar 
keywords:  
summary: Für die Integration von ServiceNow mit Insight sind verschiedene Setup-Aufgaben erforderlich. 
---
= Konfigurieren von ServiceNow für die Integration
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Für die Integration von ServiceNow mit Insight sind verschiedene Setup-Aufgaben erforderlich.



== Über diese Aufgabe

Bei der Integration von ServiceNow mit Insight müssen folgende Aufgaben durchgeführt werden:

Auf der ServiceNow-Seite:

* Rolle Auswerten
* Installieren Sie Die Updatesätze
* Benutzer einrichten


Auf der Insight-Seite:

* Fügen Sie den ServiceNow-Benutzer hinzu


Auf der Python-Steckerseite:

* Installieren Sie Python
* Installieren Sie zusätzliche Bibliotheken
* Initialisieren Sie den Anschluss
* Bearbeiten Sie die Datei config.ini
* Testen Sie den Stecker
* Synchronisieren Sie den Anschluss
* Planen Sie die tägliche Ausführung von Aufgaben


In den folgenden Abschnitten wird jeder dieser Punkte näher erläutert.
