---
permalink: howto/preparation-and-prerequisites-for-servicenow-integration.html 
sidebar: sidebar 
keywords:  
summary: Die erforderlichen Vorbereitungen und Voraussetzungen müssen für ServiceNow, Insight und den Python Middleware Connector vor der Integration erfüllt sein. 
---
= Vorbereitung und Voraussetzungen für die Integration von Service Now
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die erforderlichen Vorbereitungen und Voraussetzungen müssen für ServiceNow, Insight und den Python Middleware Connector vor der Integration erfüllt sein.



== Empfohlener Workflow

Für die Integration von ServiceNow in Insight wird folgender Workflow dringend empfohlen:

. Stellen Sie zuerst den Python Middleware Connector in Ihrer Entwicklungsinstanz bereit.
. Nachdem Sie bestätigt haben, dass alle Fehler in Ihrer Entwicklungsinstanz erkannt und behoben wurden, stellen Sie den Connector in Ihrer Test-/StufInstanz bereit.
. Nachdem Sie den korrekten Betrieb in Ihrer Staging-Instanz bestätigt haben, stellen Sie den Connector in Ihrer Produktionsinstanz bereit.


Wenn während einer dieser Phasen Probleme auftreten, befolgen Sie die Schritte zum Rollback, deaktivieren Sie den Connector, beheben Sie das Problem und setzen Sie ihn erneut ein.



== Allgemeine Voraussetzungen:

* Sie können entweder einen eigenständigen Host oder eine VM (empfohlen) oder den Insight Server Host/VM zum Hosten des Python Middleware Connectors verwenden.
* Es wird dringend empfohlen, den Insight-Produktionsserver zu sichern und in einer Entwicklungsinstanz bereitzustellen.
* ServiceNow muss Server in der CMDB genau erkennen.
* Insight muss die Storage- und Computing-Umgebungen präzise erkennen.
* Port 443 und 80 zur Insight Server und ServiceNow Instanz.




== ServiceNow-Voraussetzungen:

* Es wird dringend empfohlen, eine Test-/Entwicklungsinstanz zu verwenden.
* Berechtigung zum Laden von ServiceNow-Updatesätzen.
* Berechtigung zum Erstellen von Benutzern.
* ServiceNow Version Jakarta oder höher




== Voraussetzungen für Insight:

* Es wird dringend empfohlen, eine Test-/Entwicklungsinstanz zu verwenden.
* Berechtigung zum Erstellen von Benutzern (Administratorberechtigungen).
* Insight Version 7.3.1 oder höher wird unterstützt. Verwenden Sie zur optimalen Nutzung der Insight jedoch die neueste Version.




== Voraussetzungen für den Python Middleware Connector:

* Python Version 3.6 oder höher installiert.
* Aktivieren Sie bei der Installation von Python das Kontrollkästchen, um alle Benutzer zu aktivieren. Dies setzt Python für Standard-Installationsorte von Anwendungen.
* Aktivieren Sie bei der Installation von Python das Kontrollkästchen, damit der Installer den Pfad aktualisieren kann. Andernfalls müssen Sie den Pfad manuell aktualisieren.
* Laden Sie die Bibliotheken Python *pysnow* und *Requests* herunter.

