---
sidebar: sidebar 
permalink: task_config_telegraf_dcos.html 
keywords: telegraf, installation, install, dcos 
summary: dcos-Konfiguration 
---
= DC/OS Data Collector
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Insights verwendet diese Datenerfassung zum Erfassen von Kennzahlen aus DC/OS.



== Installation

. Klicken Sie unter *Observability > Collectors* auf *+Data Collector*. Wählen Sie *DC/OS*.
+
Wenn Sie keinen Agenten für die Sammlung konfiguriert haben, werden Sie aufgefordert link:task_config_telegraf_agent.html["Installieren Sie einen Agenten"] Ihrer Umgebung zu unterstützen.

+
Wenn Sie bereits einen Agenten konfiguriert haben, wählen Sie das entsprechende Betriebssystem oder die entsprechende Plattform aus, und klicken Sie auf *Weiter*.

. Befolgen Sie die Anweisungen im Bildschirm DC/OS-Konfiguration, um den Datensammler zu konfigurieren. Die Anweisungen hängen vom Betriebssystem oder der Plattform ab, die Sie zur Datenerfassung verwenden.




== Einrichtung

Informationen zur Einrichtung finden Sie im https://docs.mesosphere.com["DC/OS-Dokumentation"].



== Objekte und Zähler

Folgende Objekte und ihre Zähler werden gesammelt:

[cols="<.<,<.<,<.<,<.<"]
|===
| Objekt | Identifikatoren | Merkmale | Datenpunkte 


| dcos_Node | dcos_Container
dcos_App | Cluster
Hostname
Pfad (nur Dateisystemfelder)
Schnittstelle (nur Netzwerkfelder)
Container_id
Task_Name | System_Betriebszeit (float)
cpu_Cores (Float)
cpu_gesamt (float)
cpu_User (float)
cpu_System (Float)
cpu_Leerlauf (float)
cpu_Wait (float)
Last_1min (Float)
Last_5min (float)
Last_15min (Float)
Filesystem_Capacity_total_Bytes (int)
Filesystem_Capacity_used_Bytes (int)
Filesystem_Capacity_free_Bytes (int)
Filesystem_Inode_total (float)
Filesystem_Inode_used (float)
Filesystem_Inode_free (float)
Memory_total_Bytes (int)
Memory_free_Bytes (int)
Memory_Buffer_Bytes (int)
Memory_cached_Bytes (int)
Swap_total_Bytes (int)
Swap_free_Bytes (int)
Swap_used_Bytes (int)
Network_in_Bytes (int)
Network_out_Bytes (int)
Network_in_Packets (float)
Network_out_Packets (float)
Network_in_dropped (float)
Network_out_dropped (float)
Network_in_errors (float)
Network_out_errors (float)
Prozessanzahl (float) 
|===


== Fehlerbehebung

Weitere Informationen finden Sie im link:concept_requesting_support.html["Unterstützung"] Seite.
