---
sidebar: sidebar 
permalink: task_config_telegraf_consul.html 
keywords: telegraf, installation, install, consul 
summary: Konfiguration des Consul-Datensammlers 
---
= Consul Data Collector
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Insights verwendet diesen Datensammler, um Metriken von Consul zu erfassen.



== Installation

. Klicken Sie unter *Observability > Collectors* auf *+Data Collector*. Wählen Sie Konsul.
+
Wenn Sie keinen Agenten für die Sammlung konfiguriert haben, werden Sie aufgefordert link:task_config_telegraf_agent.html["Installieren Sie einen Agenten"] Ihrer Umgebung zu unterstützen.

+
Wenn Sie bereits einen Agenten konfiguriert haben, wählen Sie das entsprechende Betriebssystem oder die entsprechende Plattform aus, und klicken Sie auf *Weiter*.

. Befolgen Sie die Anweisungen auf dem Bildschirm Consul Configuration, um den Datensammler zu konfigurieren. Die Anweisungen hängen vom Betriebssystem oder der Plattform ab, die Sie zur Datenerfassung verwenden.




== Einrichtung

Informationen finden Sie unter link:https://www.consul.io/docs/index.html["Dokumentation für Konsul"].



== Objekte und Zähler für Konsul

Folgende Objekte und ihre Zähler werden gesammelt:

[cols="<.<,<.<,<.<,<.<"]
|===
| Objekt: | Kennungen: | Attribute: | Datenpunkte: 


| Konsul | Namespace
ID prüfen
Service-Knoten | Knoten-IP
Node-BS
Node-UUID
Node-Name
Name Des Service
Prüfen Sie Den Namen
Service-ID
Status | Kritisch
Bestehen
Warnung 
|===


== Fehlerbehebung

Weitere Informationen finden Sie im link:concept_requesting_support.html["Unterstützung"] Seite.
