---
sidebar: sidebar 
permalink: task_config_telegraf_kubernetes.html 
keywords: telegraf, installation, install, kubernetes 
summary: Kubernetes-Konfiguration für den Data Collector 
---
= Kubernetes Data Collector
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Insights verwendet diese Datensammler, um Kubernetes Pod, Node und Container-Kennzahlen zu erfassen.



== Installation

Eine Anleitung zur Kubernetes Installation finden Sie im link:task_config_telegraf_agent.html#kubernetes["Agenteninstallation"] Seite.


NOTE: Informationen über *kube-State-metrics* wurden in die verschoben link:task_config_telegraf_agent.html#kubernetes["Agenteninstallation"] Seite.



== Objekte und Zähler

Folgende Objekte und ihre Zähler werden gesammelt:

[cols="<.<,<.<,<.<,<.<"]
|===
| Objekt: | Kennungen: | Attribute: | Datenpunkte: 


| Kubernetes Container | Namespace
Pod
Container
Cluster | Kubernetes Node
Node-Name
Node-BS
Node-UUID
Knoten-IP | CPU-Nanosekunden
CPU-Auslastung Nanocores
Hauptfehler Der Speicherseite
Speicherresident Set Size (RSS)
Speicher-Arbeitsdatensatz
Fehler Auf Der Speicherseite
Speicherauslastung
Root-Dateisystem Verfügbar
Root-Dateisystemkapazität
Root-Dateisystem Verwendet 


| Kubernetes Node | Kubernetes Node
Cluster | Node-Name
Node-BS
Node-UUID
Knoten-IP | CPU-Auslastung Nanocores
CPU-Auslastung Nanosekunden
Dateisystem Verfügbar
Dateisystem Insgesamt
Verwendetes Dateisystem
Verfügbarer Speicher
Speicherauslastung
Hauptfehler Der Speicherseite
Fehler Auf Der Speicherseite
Speicherresident Set Size (RSS)
Speicher-Arbeitsdatensatz
Netzwerk-RX-Fehler (pro Sekunde)
Netzwerk-RX-Byte (pro Sekunde)
Netzwerk-TX-Fehler (pro Sekunde)
Netzwerk-TX Byte (pro Sekunde)
Laufzeitbild-Dateisystem Verfügbar
Verwendetes Laufzeitbild-Dateisystem
Laufzeitabbild Dateisystemkapazität 


| Kubernetes Pod | Namespace
Pod
Cluster | Kubernetes Node
Node-Name
Knoten-IP
Node-BS
Node-UUID | Netzwerk-TX Byte (pro Sekunde)
Netzwerk-TX-Fehler (pro Sekunde)
Netzwerk-RX-Byte (pro Sekunde)
Netzwerk-RX-Fehler (pro Sekunde) 


| Kubernetes Pod Volume | Datenmenge
Pod
Cluster
Namespace | Kubernetes Node
Node-Name
Node-UUID
Knoten-IP
Node-BS | Verfügbar
Kapazität
Verwendet 


| Kubernetes System-Container | System-Container
Kubernetes Node
Cluster | Node-Name
Knoten-IP
Node-BS
Node-UUID | CPU-Auslastung Nanocores
CPU-Auslastung Kern Nanosekunden
Hauptfehler Der Speicherseite
Fehler Auf Der Speicherseite
Speicherresident Set Size (RSS)
Speicherauslastung
Speicher-Arbeitsdatensatz
Root-Dateisystem Verfügbar
Root-Dateisystemkapazität
Protokolle Dateisystem Verfügbar
Protokolliert Die Kapazität Des Dateisystems 
|===


== Fehlerbehebung

[cols="2*"]
|===
| Problem: | Versuchen Sie dies: 


| Ich habe den Kubernetes Agent Installer-Befehl ausgeführt, aber ich sehe keinen Telegraf Agent-Pod über:

 Sudo kubectl --Namespace CI-Monitoring get Pods | Prüfen Sie, ob beim Bereitstellen des DemonSet Fehler aufgetreten sind:

 Sudo kubectl --Namespace CI-Monitoring Beschreiben Sie ds telegraf-ds

Wenn Fehler in Bezug auf SecurityContextConstraints auftreten, gehen Sie wie folgt vor:

1. Generieren Sie die Telegraf DemonSet YAML

 Sudo kubectl --Namespace CI-Monitoring get ds telegraf-ds -o yaml > /tmp/telegraf-ds.yaml

2. Stoppen Sie den Telegraf Service

 Sudo kubectl --Namespace CI-Monitoring delete ds telegraf-ds

3. Erstellen Sie die erforderliche SecurityContextConstraint (siehe Abschnitt „Konfigurieren des Agenten zum Sammeln von Daten“)

4. Erstellen Sie das Telegraf DemonSet neu 


| Ich habe Telegraf so konfiguriert, dass er Informationen über meinen Kubernetes Cluster erhält, aber in Cloud Insights sind keine Informationen zu finden. Ich sehe „Ungültige Header field value“ Fehler in der Telegraf log Datei, die sich auf das kubernetes Input Plugin beziehen, das ich konfiguriert habe. | Stellen Sie sicher, dass die referenzierte Inhabertoken-Datei keine nachgestellte Newline hat. Führen Sie zum Überprüfen den folgenden Befehl aus, und bestätigen Sie, dass er 0 zurückgibt:

 Tail -c1 <bearer_token_file> 
|===
Weitere Informationen finden Sie im link:concept_requesting_support.html["Unterstützung"] Seite.
