---
sidebar: sidebar 
permalink: telegraf_agent_k8s_config_options.html 
keywords: telegraf, installation, install, agent, telegraf agent, kubernetes, eks, operator, k8s, options, configuration 
summary: Der NetApp Kubernetes Monitoring Operator verfügt über eine Reihe konfigurierbarer Optionen. 
---
= Konfigurationsoptionen für NetApp Kubernetes Monitoring Operator
:hardbreaks:
:toclevels: 2
:allow-uri-read: 
:nofooter: 
:toclevels: 2
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Der link:task_config_telegraf_agent_k8s.html["NetApp Kubernetes Monitoring Operator"] Installation und Konfiguration können individuell angepasst werden.

In der folgenden Tabelle sind die möglichen Optionen für die AgentConfiguration-Datei aufgeführt:

[cols="1,1,2"]
|===
| Komponente | Option | Beschreibung 


| Agent |  | Konfigurationsoptionen, die allen Komponenten gemeinsam sind, die der Bediener installieren kann. Diese können als "globale" Optionen betrachtet werden. 


|  | DockerRepo | Ein ockerRepo override, um Bilder von Kunden private Docker-Repos im Vergleich zu Cloud Insights Docker Repo zu ziehen. Der Standardwert ist Cloud Insights Docker Repo 


|  | DockerImagePullSecret | Optional: Ein Geheimnis für den Kunden private repo 


|  | ClusterName | Freitextfeld, das einen Cluster über alle Kundencluster eindeutig identifiziert. Diese sollte bei einem Cloud Insights-Mandanten eindeutig sein. Der Standardwert ist das, was der Kunde in die Benutzeroberfläche für das Feld „Cluster Name“ eingibt 


|  | Proxy
Format:
Proxy:
  Server:
  Anschluss:
  Benutzername:
  Kennwort:
  Noproxy:
  IsTelegrafProxyEnabled:
  IsAuProxyEnabled:
  IsFluentbitProxyEnabled:
  IsCollectorProxyEnabled: | Optional für den Kunden zum Festlegen des Proxys. Dies ist in der Regel Kunden Corporate Proxy. 


| telegraf |  | Konfigurationsoptionen, mit denen die telegraf-Installation des Bedieners angepasst werden kann 


|  | Erfassungsintervall | Messgrößen-Erfassungsintervall, in Sekunden (max. = 60 s) 


|  | DsCpuLimit | CPU-Limit für telegraf ds 


|  | DsMemLimit | Speicherlimit für telegraf ds 


|  | DsCpuRequest | CPU-Anforderung für telegraf ds 


|  | DsMemRequest | Speicheranforderung für telegraf ds 


|  | RsCpuLimit | CPU-Limit für telegraf rs 


|  | RsMemLimit | Speichergrenze für telegraf rs 


|  | RsCpuRequest | CPU-Anforderung für telegraf rs 


|  | RsMemRequest | Speicheranforderung für telegraf rs 


|  | DockerMountPoint | Eine Überschreibung für dockerMountPoint-Pfad. Dies gilt für nicht standardmäßige Docker-Installationen auf K8s-Plattformen wie Cloud Foundry 


|  | DockerUnixSocket | Eine Überschreibung für dockerUnixSocket-Pfad. Dies gilt für nicht standardmäßige Docker-Installationen auf K8s-Plattformen wie Cloud Foundry. 


|  | CrioSockPath | Eine Überschreibung für crioSockPath-Pfad. Dies gilt für nicht standardmäßige Docker-Installationen auf K8s-Plattformen wie Cloud Foundry. 


|  | RunPrivileged | Führen Sie den telegraf Container im privilegierten Modus aus. Setzen Sie diese Einstellung auf TRUE, wenn SELinux auf Ihren K8s-Knoten aktiviert ist 


|  | Stapelgröße | Siehe link:https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md#agent["Telegraf-Konfigurationsdokumentation"] 


|  | BufferLimit | Siehe link:https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md#agent["Telegraf-Konfigurationsdokumentation"] 


|  | Rundintervall | Siehe link:https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md#agent["Telegraf-Konfigurationsdokumentation"] 


|  | SammlungJitter | Siehe link:https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md#agent["Telegraf-Konfigurationsdokumentation"] 


|  | Präzision | Siehe link:https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md#agent["Telegraf-Konfigurationsdokumentation"] 


|  | Flushintervall | Siehe link:https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md#agent["Telegraf-Konfigurationsdokumentation"] 


|  | FlushJitter | Siehe link:https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md#agent["Telegraf-Konfigurationsdokumentation"] 


|  | AusgabeTimeout | Siehe link:https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md#agent["Telegraf-Konfigurationsdokumentation"] 


|  | DockerMetricCollectionEnabled | Erfassen von Docker-Kennzahlen Standardmäßig ist dieser Wert auf „true“ gesetzt, und Docker-Kennzahlen werden für lokale, Docker-basierte K8s-Bereitstellungen erfasst. Um die Erfassung der Docker-Metrik zu deaktivieren, setzen Sie diese auf FALSE. 


|  | DsToleranzen | telegraf-ds zusätzliche Toleranzen. 


|  | RsToleranzen | telegraf-rs zusätzliche Toleranzen. 


| status-Kennzahlen von kube |  | Konfigurationsoptionen, mit denen die installation von kube-Statusmetriken des Operators angepasst werden kann 


|  | CpuLimit | CPU-Limit für die bereitstellung von kube-State-Metriken 


|  | MemLimit | MEM-Limit für die implementierung von kube-State-Metriken 


|  | CpuRequest | CPU-Anforderung für die Bereitstellung von kube-Statusmetriken 


|  | MemRequest | MEM-Anforderung für die Bereitstellung von kube-Statuskennzahlen 


|  | Ressourcen | Eine kommagetrennte Liste der zu erfassenden Ressourcen.
Beispiel: Cronjobs,demonsets,Deployments,ingresses,Jobs,Namespaces,Nodes,persistent Volumeclaims,
PersistentVolumes,Pods,Replikasets,Ressourcenequotas,Services,StatusFulsets 


|  | Toleranzen | zusätzliche Toleranzen für kube-State-Metriken. 


|  | Etiketten | Eine kommagetrennte Liste von Ressourcen, die kube-State-metrics erfassen sollte

+++
Beispiel: Cronjobs=[*],demonsets=[*],Deployments=[*],ingresses=[*],Jobs=[*],Namespaces=[*],Nodes=[*],
Persistent volumeclaims=[*],persistent Volumes=[*],Pods=[*],replikasets=[*],resourcequotas=[*],Services=[*],statefulsets=[*]
+++ 


| Protokolle |  | Konfigurationsoptionen, mit denen die Protokollsammlung und die Installation des Bedieners angepasst werden können 


|  | Wieder FromHead | Wahr/falsch, sollte fließendes Bit das Protokoll vom Kopf lesen 


|  | Zeitüberschreitung | Timeout in Sekunden 


|  | DnsMode | TCP/UDP, Modus für DNS 


|  | Fluent-Bit-Tolerationen | Fluent-Bit-ds zusätzliche Toleranzen. 


|  | Ereignis-Exporteur-Tolerationen | Ereignis-Exporteur zusätzliche Toleranzen. 


| Workload-Zuordnung |  | Konfigurationsoptionen, mit denen die Erfassung der Workload-Zuordnung und die Installation des Operators angepasst werden können 


|  | CpuLimit | CPU-Limit für Netto-Observer ds 


|  | MemLimit | MEM-Grenze für Netto-Beobachter ds 


|  | CpuRequest | CPU-Anforderung für Netto-Observer-ds 


|  | MemRequest | MEM-Anforderung für Netto-Beobachter ds 


|  | MetricAggregationInterval | Intervall für die metrische Aggregation in Sekunden 


|  | BpfPollInterval | BPF-Abfrageintervall in Sekunden 


|  | EnableDNSLookup | True/false, DNS-Suche aktivieren 


|  | l4-Tolerationen | NET-Observer-l4-ds zusätzliche Toleranzen. 
|===


== Beispieldatei für AgentConfiguration

Unten finden Sie eine Beispieldatei für AgentConfiguration. Beachten Sie, dass hier nicht alle Optionen erfasst werden:

[listing]
----
apiVersion: monitoring.netapp.com/v1alpha1
kind: AgentConfiguration
metadata:
  name: netapp-monitoring-configuration
  namespace: NAMESPACE_PLACEHOLDER
  labels:
    installed-by: nkmo-NAMESPACE_PLACEHOLDER

spec:
  agent:
    # a uniquely identifiable user friendly clustername. This clustername should be unique across
    # all clusters in your cloud insights tenant
    clusterName: pbhat-dev

    # optional: proxy settings. This is usually your corporate proxy settings
    proxy:
      server: testserver
      port: 3128
      noproxy: websock.svc
      username: user
      password: pass
      isTelegrafProxyEnabled: true
      isFluentbitProxyEnabled: true
      isCollectorsProxyEnabled: true
      isAuProxyEnabled: false

    # An optional docker registry where you want docker images to be pulled from as compared to CI's docker registry
    # Please see documentation link here:
    dockerRepo: dummy.docker.repo/long/path/to/test
    # Optional: A docker image pull secret that maybe needed for your private docker registry
    dockerImagePullSecret: docker-secret-name

    # Set runPrivileged to true SELinux is enabled on your kubernetes nodes
    # runPrivileged: false

  telegraf:
    # use these settings to fine tune data collection
    collectionInterval: 20s

    # batchSize:
    # bufferLimit:
    # roundInterval:
    # collectionJitter:
    # precision:
    # flushInterval:
    # flushJitter:

    # Collect kubernetes.system_container metrics and objects in the kube-system|cattle-system namespaces for managed kubernetes clusters
    # (EKS, AKS, GKE, managed Rancher). Set this to true if you want collect these metrics.
    #managedK8sSystemMetricCollectionEnabled: true|false

    # Collect kubernetes.pod_volume (pod ephemeral storage) metrics. Set this to true if you want to collect these metrics.
    #podVolumeMetricFilteringEnabled: true|false

    # Declare Rancher cluster as managed. Set this to true if your Rancher cluster is managed as opposed to on-premise.
    #isManagedRancher: true|false

    # By default, docker metrics will be collected for on-premise, docker-based k8s deployments. To disable docker metric collection, set this to false.
    # dockerMetricCollectionEnabled: true|false


    # Deamonset CPU/Mem limits and requests
    # dsCpuLimit:
    # dsMemLimit:
    # dsCpuRequest:
    # dsMemRequest:

    # Replicaset CPU/Mem limits and requests
    # rsCpuLimit:
    # rsMemLimit:
    # rsCpuRequest:
    # rsMemRequest:

  kube-state-metrics:
    # cpuLimit:
    # memLimit:
    # cpuRequest:
    # memRequest:

    # a comma separated list of resources to capture.
    # example: cronjobs,daemonsets,deployments,ingresses,jobs,namespaces,nodes,persistentvolumeclaims,persistentvolumes,pods,replicasets,resourcequotas,services,statefulsets
    # resources:

    # a comma seperated list of resources that kube-state-metrics should capture
    # example: cronjobs=[*],daemonsets=[*],deployments=[*],ingresses=[*],jobs=[*],namespaces=[*],nodes=[*],persistentvolumeclaims=[*],persistentvolumes=[*],pods=[*],replicasets=[*],resourcequotas=[*],services=[*],statefulsets=[*]
    # labels:
----